// Code generated by protoc-gen-go. DO NOT EDIT.
// source: devops.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type BuildResult_StatusCode int32

const (
	BuildResult_UNDEFINED BuildResult_StatusCode = 0
	BuildResult_SUCCESS   BuildResult_StatusCode = 1
	BuildResult_FAILURE   BuildResult_StatusCode = 2
)

var BuildResult_StatusCode_name = map[int32]string{
	0: "UNDEFINED",
	1: "SUCCESS",
	2: "FAILURE",
}
var BuildResult_StatusCode_value = map[string]int32{
	"UNDEFINED": 0,
	"SUCCESS":   1,
	"FAILURE":   2,
}

func (x BuildResult_StatusCode) String() string {
	return proto.EnumName(BuildResult_StatusCode_name, int32(x))
}
func (BuildResult_StatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{4, 0} }

// Secret is a temporary object to establish security with the Devops.
// A better solution using certificate will be introduced later
type Secret struct {
	EnrollId     string `protobuf:"bytes,1,opt,name=enrollId" json:"enrollId,omitempty"`
	EnrollSecret string `protobuf:"bytes,2,opt,name=enrollSecret" json:"enrollSecret,omitempty"`
}

func (m *Secret) Reset()                    { *m = Secret{} }
func (m *Secret) String() string            { return proto.CompactTextString(m) }
func (*Secret) ProtoMessage()               {}
func (*Secret) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *Secret) GetEnrollId() string {
	if m != nil {
		return m.EnrollId
	}
	return ""
}

func (m *Secret) GetEnrollSecret() string {
	if m != nil {
		return m.EnrollSecret
	}
	return ""
}

type SigmaInput struct {
	Secret   *Secret `protobuf:"bytes,1,opt,name=secret" json:"secret,omitempty"`
	AppTCert []byte  `protobuf:"bytes,2,opt,name=appTCert,proto3" json:"appTCert,omitempty"`
	Data     []byte  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *SigmaInput) Reset()                    { *m = SigmaInput{} }
func (m *SigmaInput) String() string            { return proto.CompactTextString(m) }
func (*SigmaInput) ProtoMessage()               {}
func (*SigmaInput) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *SigmaInput) GetSecret() *Secret {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *SigmaInput) GetAppTCert() []byte {
	if m != nil {
		return m.AppTCert
	}
	return nil
}

func (m *SigmaInput) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ExecuteWithBinding struct {
	ChaincodeInvocationSpec *ChaincodeInvocationSpec `protobuf:"bytes,1,opt,name=chaincodeInvocationSpec" json:"chaincodeInvocationSpec,omitempty"`
	Binding                 []byte                   `protobuf:"bytes,2,opt,name=binding,proto3" json:"binding,omitempty"`
}

func (m *ExecuteWithBinding) Reset()                    { *m = ExecuteWithBinding{} }
func (m *ExecuteWithBinding) String() string            { return proto.CompactTextString(m) }
func (*ExecuteWithBinding) ProtoMessage()               {}
func (*ExecuteWithBinding) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *ExecuteWithBinding) GetChaincodeInvocationSpec() *ChaincodeInvocationSpec {
	if m != nil {
		return m.ChaincodeInvocationSpec
	}
	return nil
}

func (m *ExecuteWithBinding) GetBinding() []byte {
	if m != nil {
		return m.Binding
	}
	return nil
}

type SigmaOutput struct {
	Tcert        []byte `protobuf:"bytes,1,opt,name=tcert,proto3" json:"tcert,omitempty"`
	Sigma        []byte `protobuf:"bytes,2,opt,name=sigma,proto3" json:"sigma,omitempty"`
	Asn1Encoding []byte `protobuf:"bytes,3,opt,name=asn1Encoding,proto3" json:"asn1Encoding,omitempty"`
}

func (m *SigmaOutput) Reset()                    { *m = SigmaOutput{} }
func (m *SigmaOutput) String() string            { return proto.CompactTextString(m) }
func (*SigmaOutput) ProtoMessage()               {}
func (*SigmaOutput) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *SigmaOutput) GetTcert() []byte {
	if m != nil {
		return m.Tcert
	}
	return nil
}

func (m *SigmaOutput) GetSigma() []byte {
	if m != nil {
		return m.Sigma
	}
	return nil
}

func (m *SigmaOutput) GetAsn1Encoding() []byte {
	if m != nil {
		return m.Asn1Encoding
	}
	return nil
}

type BuildResult struct {
	Status         BuildResult_StatusCode   `protobuf:"varint,1,opt,name=status,enum=protos.BuildResult_StatusCode" json:"status,omitempty"`
	Msg            string                   `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	DeploymentSpec *ChaincodeDeploymentSpec `protobuf:"bytes,3,opt,name=deploymentSpec" json:"deploymentSpec,omitempty"`
}

func (m *BuildResult) Reset()                    { *m = BuildResult{} }
func (m *BuildResult) String() string            { return proto.CompactTextString(m) }
func (*BuildResult) ProtoMessage()               {}
func (*BuildResult) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *BuildResult) GetStatus() BuildResult_StatusCode {
	if m != nil {
		return m.Status
	}
	return BuildResult_UNDEFINED
}

func (m *BuildResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *BuildResult) GetDeploymentSpec() *ChaincodeDeploymentSpec {
	if m != nil {
		return m.DeploymentSpec
	}
	return nil
}

type TransactionRequest struct {
	TransactionUuid string `protobuf:"bytes,1,opt,name=transactionUuid" json:"transactionUuid,omitempty"`
}

func (m *TransactionRequest) Reset()                    { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()               {}
func (*TransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *TransactionRequest) GetTransactionUuid() string {
	if m != nil {
		return m.TransactionUuid
	}
	return ""
}

func init() {
	proto.RegisterType((*Secret)(nil), "protos.Secret")
	proto.RegisterType((*SigmaInput)(nil), "protos.SigmaInput")
	proto.RegisterType((*ExecuteWithBinding)(nil), "protos.ExecuteWithBinding")
	proto.RegisterType((*SigmaOutput)(nil), "protos.SigmaOutput")
	proto.RegisterType((*BuildResult)(nil), "protos.BuildResult")
	proto.RegisterType((*TransactionRequest)(nil), "protos.TransactionRequest")
	proto.RegisterEnum("protos.BuildResult_StatusCode", BuildResult_StatusCode_name, BuildResult_StatusCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Devops service

type DevopsClient interface {
	// Log in - passed Secret object and returns Response object, where
	// msg is the security context to be used in subsequent invocations
	Login(ctx context.Context, in *Secret, opts ...grpc.CallOption) (*Response, error)
	// Build the chaincode package.
	Build(ctx context.Context, in *ChaincodeSpec, opts ...grpc.CallOption) (*ChaincodeDeploymentSpec, error)
	// Deploy the chaincode package to the chain.
	Deploy(ctx context.Context, in *ChaincodeSpec, opts ...grpc.CallOption) (*ChaincodeDeploymentSpec, error)
	// Invoke chaincode.
	Invoke(ctx context.Context, in *ChaincodeInvocationSpec, opts ...grpc.CallOption) (*Response, error)
	// Query chaincode.
	Query(ctx context.Context, in *ChaincodeInvocationSpec, opts ...grpc.CallOption) (*Response, error)
}

type devopsClient struct {
	cc *grpc.ClientConn
}

func NewDevopsClient(cc *grpc.ClientConn) DevopsClient {
	return &devopsClient{cc}
}

func (c *devopsClient) Login(ctx context.Context, in *Secret, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Devops/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) Build(ctx context.Context, in *ChaincodeSpec, opts ...grpc.CallOption) (*ChaincodeDeploymentSpec, error) {
	out := new(ChaincodeDeploymentSpec)
	err := grpc.Invoke(ctx, "/protos.Devops/Build", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) Deploy(ctx context.Context, in *ChaincodeSpec, opts ...grpc.CallOption) (*ChaincodeDeploymentSpec, error) {
	out := new(ChaincodeDeploymentSpec)
	err := grpc.Invoke(ctx, "/protos.Devops/Deploy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) Invoke(ctx context.Context, in *ChaincodeInvocationSpec, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Devops/Invoke", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) Query(ctx context.Context, in *ChaincodeInvocationSpec, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Devops/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Devops service

type DevopsServer interface {
	// Log in - passed Secret object and returns Response object, where
	// msg is the security context to be used in subsequent invocations
	Login(context.Context, *Secret) (*Response, error)
	// Build the chaincode package.
	Build(context.Context, *ChaincodeSpec) (*ChaincodeDeploymentSpec, error)
	// Deploy the chaincode package to the chain.
	Deploy(context.Context, *ChaincodeSpec) (*ChaincodeDeploymentSpec, error)
	// Invoke chaincode.
	Invoke(context.Context, *ChaincodeInvocationSpec) (*Response, error)
	// Query chaincode.
	Query(context.Context, *ChaincodeInvocationSpec) (*Response, error)
}

func RegisterDevopsServer(s *grpc.Server, srv DevopsServer) {
	s.RegisterService(&_Devops_serviceDesc, srv)
}

func _Devops_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Secret)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).Login(ctx, req.(*Secret))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChaincodeSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/Build",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).Build(ctx, req.(*ChaincodeSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChaincodeSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).Deploy(ctx, req.(*ChaincodeSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChaincodeInvocationSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).Invoke(ctx, req.(*ChaincodeInvocationSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChaincodeInvocationSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).Query(ctx, req.(*ChaincodeInvocationSpec))
	}
	return interceptor(ctx, in, info, handler)
}

var _Devops_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Devops",
	HandlerType: (*DevopsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Devops_Login_Handler,
		},
		{
			MethodName: "Build",
			Handler:    _Devops_Build_Handler,
		},
		{
			MethodName: "Deploy",
			Handler:    _Devops_Deploy_Handler,
		},
		{
			MethodName: "Invoke",
			Handler:    _Devops_Invoke_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Devops_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "devops.proto",
}

func init() { proto.RegisterFile("devops.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 503 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x51, 0x6f, 0xd3, 0x3c,
	0x14, 0x6d, 0xda, 0xaf, 0xd9, 0xb7, 0xdb, 0xd2, 0x55, 0x57, 0x20, 0xaa, 0x3e, 0x00, 0xf2, 0x03,
	0x9a, 0x84, 0x54, 0x89, 0x22, 0x78, 0x02, 0xa4, 0xb5, 0xcd, 0xa0, 0xd2, 0x34, 0x84, 0xb3, 0x0a,
	0xf1, 0xc0, 0x83, 0x9b, 0x98, 0xce, 0x22, 0xb5, 0x43, 0xec, 0x4c, 0xec, 0x27, 0xf0, 0x93, 0xf8,
	0x25, 0xfc, 0x1d, 0x64, 0x3b, 0xe9, 0x68, 0xd9, 0x34, 0x09, 0x9e, 0xe2, 0x73, 0x7c, 0xee, 0x3d,
	0x39, 0x37, 0x57, 0x81, 0x6e, 0xca, 0x2f, 0x54, 0xae, 0x47, 0x79, 0xa1, 0x8c, 0xc2, 0xd0, 0x3d,
	0xf4, 0xf0, 0x20, 0x39, 0x67, 0x42, 0x26, 0x2a, 0xe5, 0xfe, 0x62, 0xd8, 0xfd, 0xcc, 0x96, 0x85,
	0x48, 0x3c, 0x22, 0x6f, 0x21, 0x8c, 0x79, 0x52, 0x70, 0x83, 0x43, 0xf8, 0x9f, 0xcb, 0x42, 0x65,
	0xd9, 0x3c, 0x1d, 0x04, 0x8f, 0x82, 0xc3, 0x7d, 0xba, 0xc1, 0x48, 0xa0, 0xeb, 0xcf, 0x5e, 0x3b,
	0x68, 0xba, 0xfb, 0x2d, 0x8e, 0xa4, 0x00, 0xb1, 0x58, 0xad, 0xd9, 0x5c, 0xe6, 0xa5, 0xc1, 0xc7,
	0x10, 0x6a, 0xaf, 0xb5, 0xbd, 0x3a, 0xe3, 0x9e, 0xf7, 0xd3, 0x23, 0xaf, 0xa6, 0xd5, 0xad, 0x75,
	0x65, 0x79, 0x7e, 0x36, 0xe5, 0x85, 0xef, 0xda, 0xa5, 0x1b, 0x8c, 0x08, 0xff, 0xa5, 0xcc, 0xb0,
	0x41, 0xcb, 0xf1, 0xee, 0x4c, 0xbe, 0x07, 0x80, 0xd1, 0x37, 0x9e, 0x94, 0x86, 0x7f, 0x10, 0xe6,
	0x7c, 0x22, 0x64, 0x2a, 0xe4, 0x0a, 0x3f, 0xc2, 0xfd, 0x4d, 0xce, 0xb9, 0xbc, 0x50, 0x09, 0x33,
	0x42, 0xc9, 0x38, 0xe7, 0x49, 0xe5, 0xff, 0xb0, 0xf6, 0x9f, 0x5e, 0x2f, 0xa3, 0x37, 0xd5, 0xe3,
	0x00, 0xf6, 0x96, 0xde, 0xa5, 0x7a, 0xc1, 0x1a, 0x92, 0x4f, 0xd0, 0x71, 0x89, 0xdf, 0x95, 0xc6,
	0x46, 0xbe, 0x0b, 0x6d, 0x93, 0xd8, 0x1c, 0x81, 0x93, 0x79, 0x60, 0x59, 0x6d, 0x45, 0x55, 0xb1,
	0x07, 0x76, 0xa0, 0x4c, 0xcb, 0xa7, 0x91, 0x35, 0xb4, 0x9d, 0x7d, 0xc4, 0x2d, 0x8e, 0xfc, 0x0c,
	0xa0, 0x33, 0x29, 0x45, 0x96, 0x52, 0xae, 0xcb, 0xcc, 0xe0, 0x0b, 0x08, 0xb5, 0x61, 0xa6, 0xd4,
	0xce, 0xa0, 0x37, 0x7e, 0x50, 0x47, 0xfa, 0x4d, 0x34, 0x8a, 0x9d, 0x62, 0xaa, 0x52, 0x4e, 0x2b,
	0x35, 0xf6, 0xa1, 0xb5, 0xd6, 0xab, 0xea, 0x9b, 0xd9, 0x23, 0xbe, 0x81, 0x5e, 0xca, 0xf3, 0x4c,
	0x5d, 0xae, 0xb9, 0x34, 0x6e, 0x48, 0xad, 0x1b, 0x86, 0x34, 0xdb, 0x92, 0xd1, 0x9d, 0x32, 0xf2,
	0x1c, 0xe0, 0xca, 0x10, 0xef, 0xc0, 0xfe, 0xe2, 0x74, 0x16, 0x1d, 0xcf, 0x4f, 0xa3, 0x59, 0xbf,
	0x81, 0x1d, 0xd8, 0x8b, 0x17, 0xd3, 0x69, 0x14, 0xc7, 0xfd, 0xc0, 0x82, 0xe3, 0xa3, 0xf9, 0xc9,
	0x82, 0x46, 0xfd, 0x26, 0x79, 0x0d, 0x78, 0x56, 0x30, 0xa9, 0x59, 0x62, 0xa7, 0x4c, 0xf9, 0xd7,
	0x92, 0x6b, 0x83, 0x87, 0x70, 0x60, 0xae, 0xd8, 0x45, 0x29, 0xea, 0x3d, 0xdc, 0xa5, 0xc7, 0x3f,
	0x9a, 0x10, 0xce, 0xdc, 0xb2, 0xe3, 0x13, 0x68, 0x9f, 0xa8, 0x95, 0x90, 0xb8, 0xb3, 0x60, 0xc3,
	0x7e, 0x8d, 0x29, 0xd7, 0xb9, 0x92, 0x9a, 0x93, 0x06, 0x1e, 0x41, 0xdb, 0xcd, 0x0a, 0xef, 0xfd,
	0x11, 0xd4, 0xc6, 0x19, 0xde, 0x96, 0x9f, 0x34, 0x70, 0x62, 0x9d, 0x2d, 0xf7, 0x0f, 0x3d, 0x5e,
	0x41, 0x68, 0x77, 0xec, 0x0b, 0xc7, 0xdb, 0xb6, 0xf2, 0xda, 0x14, 0x2f, 0xa1, 0xfd, 0xbe, 0xe4,
	0xc5, 0xe5, 0x5f, 0x55, 0x2f, 0xfd, 0x7f, 0xe1, 0xd9, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x18,
	0x45, 0x3e, 0x26, 0x2e, 0x04, 0x00, 0x00,
}
