// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fabric.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Transaction_Type int32

const (
	Transaction_UNDEFINED Transaction_Type = 0
	// deploy a chaincode to the network and call `Init` function
	Transaction_CHAINCODE_DEPLOY Transaction_Type = 1
	// call a chaincode `Invoke` function as a transaction
	Transaction_CHAINCODE_INVOKE Transaction_Type = 2
	// call a chaincode `query` function
	Transaction_CHAINCODE_QUERY Transaction_Type = 3
	// terminate a chaincode; not implemented yet
	Transaction_CHAINCODE_TERMINATE Transaction_Type = 4
)

var Transaction_Type_name = map[int32]string{
	0: "UNDEFINED",
	1: "CHAINCODE_DEPLOY",
	2: "CHAINCODE_INVOKE",
	3: "CHAINCODE_QUERY",
	4: "CHAINCODE_TERMINATE",
}
var Transaction_Type_value = map[string]int32{
	"UNDEFINED":           0,
	"CHAINCODE_DEPLOY":    1,
	"CHAINCODE_INVOKE":    2,
	"CHAINCODE_QUERY":     3,
	"CHAINCODE_TERMINATE": 4,
}

func (x Transaction_Type) String() string {
	return proto.EnumName(Transaction_Type_name, int32(x))
}
func (Transaction_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{0, 0} }

type PeerEndpoint_Type int32

const (
	PeerEndpoint_UNDEFINED     PeerEndpoint_Type = 0
	PeerEndpoint_VALIDATOR     PeerEndpoint_Type = 1
	PeerEndpoint_NON_VALIDATOR PeerEndpoint_Type = 2
)

var PeerEndpoint_Type_name = map[int32]string{
	0: "UNDEFINED",
	1: "VALIDATOR",
	2: "NON_VALIDATOR",
}
var PeerEndpoint_Type_value = map[string]int32{
	"UNDEFINED":     0,
	"VALIDATOR":     1,
	"NON_VALIDATOR": 2,
}

func (x PeerEndpoint_Type) String() string {
	return proto.EnumName(PeerEndpoint_Type_name, int32(x))
}
func (PeerEndpoint_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{8, 0} }

type Message_Type int32

const (
	Message_UNDEFINED               Message_Type = 0
	Message_DISC_HELLO              Message_Type = 1
	Message_DISC_DISCONNECT         Message_Type = 2
	Message_DISC_GET_PEERS          Message_Type = 3
	Message_DISC_PEERS              Message_Type = 4
	Message_DISC_NEWMSG             Message_Type = 5
	Message_CHAIN_TRANSACTION       Message_Type = 6
	Message_SYNC_GET_BLOCKS         Message_Type = 11
	Message_SYNC_BLOCKS             Message_Type = 12
	Message_SYNC_BLOCK_ADDED        Message_Type = 13
	Message_SYNC_STATE_GET_SNAPSHOT Message_Type = 14
	Message_SYNC_STATE_SNAPSHOT     Message_Type = 15
	Message_SYNC_STATE_GET_DELTAS   Message_Type = 16
	Message_SYNC_STATE_DELTAS       Message_Type = 17
	Message_RESPONSE                Message_Type = 20
	Message_CONSENSUS               Message_Type = 21
)

var Message_Type_name = map[int32]string{
	0:  "UNDEFINED",
	1:  "DISC_HELLO",
	2:  "DISC_DISCONNECT",
	3:  "DISC_GET_PEERS",
	4:  "DISC_PEERS",
	5:  "DISC_NEWMSG",
	6:  "CHAIN_TRANSACTION",
	11: "SYNC_GET_BLOCKS",
	12: "SYNC_BLOCKS",
	13: "SYNC_BLOCK_ADDED",
	14: "SYNC_STATE_GET_SNAPSHOT",
	15: "SYNC_STATE_SNAPSHOT",
	16: "SYNC_STATE_GET_DELTAS",
	17: "SYNC_STATE_DELTAS",
	20: "RESPONSE",
	21: "CONSENSUS",
}
var Message_Type_value = map[string]int32{
	"UNDEFINED":               0,
	"DISC_HELLO":              1,
	"DISC_DISCONNECT":         2,
	"DISC_GET_PEERS":          3,
	"DISC_PEERS":              4,
	"DISC_NEWMSG":             5,
	"CHAIN_TRANSACTION":       6,
	"SYNC_GET_BLOCKS":         11,
	"SYNC_BLOCKS":             12,
	"SYNC_BLOCK_ADDED":        13,
	"SYNC_STATE_GET_SNAPSHOT": 14,
	"SYNC_STATE_SNAPSHOT":     15,
	"SYNC_STATE_GET_DELTAS":   16,
	"SYNC_STATE_DELTAS":       17,
	"RESPONSE":                20,
	"CONSENSUS":               21,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (Message_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{12, 0} }

type Response_StatusCode int32

const (
	Response_UNDEFINED Response_StatusCode = 0
	Response_SUCCESS   Response_StatusCode = 200
	Response_FAILURE   Response_StatusCode = 500
)

var Response_StatusCode_name = map[int32]string{
	0:   "UNDEFINED",
	200: "SUCCESS",
	500: "FAILURE",
}
var Response_StatusCode_value = map[string]int32{
	"UNDEFINED": 0,
	"SUCCESS":   200,
	"FAILURE":   500,
}

func (x Response_StatusCode) String() string {
	return proto.EnumName(Response_StatusCode_name, int32(x))
}
func (Response_StatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{13, 0} }

// Transaction defines a function call to a contract.
// `args` is an array of type string so that the chaincode writer can choose
// whatever format they wish for the arguments for their chaincode.
// For example, they may wish to use JSON, XML, or a custom format.
// TODO: Defined remaining fields.
type Transaction struct {
	Type Transaction_Type `protobuf:"varint,1,opt,name=type,enum=protos.Transaction_Type" json:"type,omitempty"`
	// store ChaincodeID as bytes so its encrypted value can be stored
	ChaincodeID                    []byte                     `protobuf:"bytes,2,opt,name=chaincodeID,proto3" json:"chaincodeID,omitempty"`
	Payload                        []byte                     `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata                       []byte                     `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Txid                           string                     `protobuf:"bytes,5,opt,name=txid" json:"txid,omitempty"`
	Timestamp                      *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=timestamp" json:"timestamp,omitempty"`
	ConfidentialityLevel           ConfidentialityLevel       `protobuf:"varint,7,opt,name=confidentialityLevel,enum=protos.ConfidentialityLevel" json:"confidentialityLevel,omitempty"`
	ConfidentialityProtocolVersion string                     `protobuf:"bytes,8,opt,name=confidentialityProtocolVersion" json:"confidentialityProtocolVersion,omitempty"`
	Nonce                          []byte                     `protobuf:"bytes,9,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ToValidators                   []byte                     `protobuf:"bytes,10,opt,name=toValidators,proto3" json:"toValidators,omitempty"`
	Cert                           []byte                     `protobuf:"bytes,11,opt,name=cert,proto3" json:"cert,omitempty"`
	Signature                      []byte                     `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *Transaction) GetType() Transaction_Type {
	if m != nil {
		return m.Type
	}
	return Transaction_UNDEFINED
}

func (m *Transaction) GetChaincodeID() []byte {
	if m != nil {
		return m.ChaincodeID
	}
	return nil
}

func (m *Transaction) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Transaction) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Transaction) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *Transaction) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Transaction) GetConfidentialityLevel() ConfidentialityLevel {
	if m != nil {
		return m.ConfidentialityLevel
	}
	return ConfidentialityLevel_PUBLIC
}

func (m *Transaction) GetConfidentialityProtocolVersion() string {
	if m != nil {
		return m.ConfidentialityProtocolVersion
	}
	return ""
}

func (m *Transaction) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Transaction) GetToValidators() []byte {
	if m != nil {
		return m.ToValidators
	}
	return nil
}

func (m *Transaction) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *Transaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// TransactionBlock carries a batch of transactions.
type TransactionBlock struct {
	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *TransactionBlock) Reset()                    { *m = TransactionBlock{} }
func (m *TransactionBlock) String() string            { return proto.CompactTextString(m) }
func (*TransactionBlock) ProtoMessage()               {}
func (*TransactionBlock) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *TransactionBlock) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

// TransactionResult contains the return value of a transaction. It does
// not track potential state changes that were a result of the transaction.
// txid - The unique identifier of this transaction.
// result - The return value of the transaction.
// errorCode - An error code. 5xx will be logged as a failure in the dashboard.
// error - An error string for logging an issue.
// chaincodeEvent - any event emitted by a transaction
type TransactionResult struct {
	Txid           string          `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
	Result         []byte          `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	ErrorCode      uint32          `protobuf:"varint,3,opt,name=errorCode" json:"errorCode,omitempty"`
	Error          string          `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
	ChaincodeEvent *ChaincodeEvent `protobuf:"bytes,5,opt,name=chaincodeEvent" json:"chaincodeEvent,omitempty"`
}

func (m *TransactionResult) Reset()                    { *m = TransactionResult{} }
func (m *TransactionResult) String() string            { return proto.CompactTextString(m) }
func (*TransactionResult) ProtoMessage()               {}
func (*TransactionResult) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *TransactionResult) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *TransactionResult) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *TransactionResult) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *TransactionResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *TransactionResult) GetChaincodeEvent() *ChaincodeEvent {
	if m != nil {
		return m.ChaincodeEvent
	}
	return nil
}

// Block carries The data that describes a block in the blockchain.
// version - Version used to track any protocol changes.
// timestamp - The time at which the block or transaction order
// was proposed. This may not be used by all consensus modules.
// transactions - The ordered list of transactions in the block.
// stateHash - The state hash after running transactions in this block.
// previousBlockHash - The hash of the previous block in the chain.
// consensusMetadata - Consensus modules may optionally store any
// additional metadata in this field.
// nonHashData - Data stored with the block, but not included in the blocks
// hash. This allows this data to be different per peer or discarded without
// impacting the blockchain.
type Block struct {
	Version           uint32                     `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Timestamp         *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Transactions      []*Transaction             `protobuf:"bytes,3,rep,name=transactions" json:"transactions,omitempty"`
	StateHash         []byte                     `protobuf:"bytes,4,opt,name=stateHash,proto3" json:"stateHash,omitempty"`
	PreviousBlockHash []byte                     `protobuf:"bytes,5,opt,name=previousBlockHash,proto3" json:"previousBlockHash,omitempty"`
	ConsensusMetadata []byte                     `protobuf:"bytes,6,opt,name=consensusMetadata,proto3" json:"consensusMetadata,omitempty"`
	NonHashData       *NonHashData               `protobuf:"bytes,7,opt,name=nonHashData" json:"nonHashData,omitempty"`
	Txids             []string                   `protobuf:"bytes,8,rep,name=txids" json:"txids,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *Block) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Block) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetStateHash() []byte {
	if m != nil {
		return m.StateHash
	}
	return nil
}

func (m *Block) GetPreviousBlockHash() []byte {
	if m != nil {
		return m.PreviousBlockHash
	}
	return nil
}

func (m *Block) GetConsensusMetadata() []byte {
	if m != nil {
		return m.ConsensusMetadata
	}
	return nil
}

func (m *Block) GetNonHashData() *NonHashData {
	if m != nil {
		return m.NonHashData
	}
	return nil
}

func (m *Block) GetTxids() []string {
	if m != nil {
		return m.Txids
	}
	return nil
}

// Contains information about the blockchain ledger such as height, current
// block hash, and previous block hash.
type BlockchainInfo struct {
	Height            uint64 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	CurrentBlockHash  []byte `protobuf:"bytes,2,opt,name=currentBlockHash,proto3" json:"currentBlockHash,omitempty"`
	PreviousBlockHash []byte `protobuf:"bytes,3,opt,name=previousBlockHash,proto3" json:"previousBlockHash,omitempty"`
}

func (m *BlockchainInfo) Reset()                    { *m = BlockchainInfo{} }
func (m *BlockchainInfo) String() string            { return proto.CompactTextString(m) }
func (*BlockchainInfo) ProtoMessage()               {}
func (*BlockchainInfo) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *BlockchainInfo) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockchainInfo) GetCurrentBlockHash() []byte {
	if m != nil {
		return m.CurrentBlockHash
	}
	return nil
}

func (m *BlockchainInfo) GetPreviousBlockHash() []byte {
	if m != nil {
		return m.PreviousBlockHash
	}
	return nil
}

// NonHashData is data that is recorded on the block, but not included in
// the block hash when verifying the blockchain.
// localLedgerCommitTimestamp - The time at which the block was added
// to the ledger on the local peer.
// chaincodeEvent - is an array ChaincodeEvents, one per transaction in the
// block
type NonHashData struct {
	LocalLedgerCommitTimestamp *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=localLedgerCommitTimestamp" json:"localLedgerCommitTimestamp,omitempty"`
	ChaincodeEvents            []*ChaincodeEvent          `protobuf:"bytes,2,rep,name=chaincodeEvents" json:"chaincodeEvents,omitempty"`
}

func (m *NonHashData) Reset()                    { *m = NonHashData{} }
func (m *NonHashData) String() string            { return proto.CompactTextString(m) }
func (*NonHashData) ProtoMessage()               {}
func (*NonHashData) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *NonHashData) GetLocalLedgerCommitTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.LocalLedgerCommitTimestamp
	}
	return nil
}

func (m *NonHashData) GetChaincodeEvents() []*ChaincodeEvent {
	if m != nil {
		return m.ChaincodeEvents
	}
	return nil
}

type PeerAddress struct {
	Host string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *PeerAddress) Reset()                    { *m = PeerAddress{} }
func (m *PeerAddress) String() string            { return proto.CompactTextString(m) }
func (*PeerAddress) ProtoMessage()               {}
func (*PeerAddress) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *PeerAddress) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *PeerAddress) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type PeerID struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *PeerID) Reset()                    { *m = PeerID{} }
func (m *PeerID) String() string            { return proto.CompactTextString(m) }
func (*PeerID) ProtoMessage()               {}
func (*PeerID) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func (m *PeerID) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PeerEndpoint struct {
	ID      *PeerID           `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Address string            `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Type    PeerEndpoint_Type `protobuf:"varint,3,opt,name=type,enum=protos.PeerEndpoint_Type" json:"type,omitempty"`
	PkiID   []byte            `protobuf:"bytes,4,opt,name=pkiID,proto3" json:"pkiID,omitempty"`
}

func (m *PeerEndpoint) Reset()                    { *m = PeerEndpoint{} }
func (m *PeerEndpoint) String() string            { return proto.CompactTextString(m) }
func (*PeerEndpoint) ProtoMessage()               {}
func (*PeerEndpoint) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

func (m *PeerEndpoint) GetID() *PeerID {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *PeerEndpoint) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PeerEndpoint) GetType() PeerEndpoint_Type {
	if m != nil {
		return m.Type
	}
	return PeerEndpoint_UNDEFINED
}

func (m *PeerEndpoint) GetPkiID() []byte {
	if m != nil {
		return m.PkiID
	}
	return nil
}

type PeersMessage struct {
	Peers []*PeerEndpoint `protobuf:"bytes,1,rep,name=peers" json:"peers,omitempty"`
}

func (m *PeersMessage) Reset()                    { *m = PeersMessage{} }
func (m *PeersMessage) String() string            { return proto.CompactTextString(m) }
func (*PeersMessage) ProtoMessage()               {}
func (*PeersMessage) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{9} }

func (m *PeersMessage) GetPeers() []*PeerEndpoint {
	if m != nil {
		return m.Peers
	}
	return nil
}

type PeersAddresses struct {
	Addresses []string `protobuf:"bytes,1,rep,name=addresses" json:"addresses,omitempty"`
}

func (m *PeersAddresses) Reset()                    { *m = PeersAddresses{} }
func (m *PeersAddresses) String() string            { return proto.CompactTextString(m) }
func (*PeersAddresses) ProtoMessage()               {}
func (*PeersAddresses) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{10} }

func (m *PeersAddresses) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type HelloMessage struct {
	PeerEndpoint *PeerEndpoint `protobuf:"bytes,1,opt,name=peerEndpoint" json:"peerEndpoint,omitempty"`
	// BlockchainInfo blockchainInfo = 2;
	PeerCredential []byte `protobuf:"bytes,3,opt,name=peerCredential,proto3" json:"peerCredential,omitempty"`
}

func (m *HelloMessage) Reset()                    { *m = HelloMessage{} }
func (m *HelloMessage) String() string            { return proto.CompactTextString(m) }
func (*HelloMessage) ProtoMessage()               {}
func (*HelloMessage) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{11} }

func (m *HelloMessage) GetPeerEndpoint() *PeerEndpoint {
	if m != nil {
		return m.PeerEndpoint
	}
	return nil
}

func (m *HelloMessage) GetPeerCredential() []byte {
	if m != nil {
		return m.PeerCredential
	}
	return nil
}

type Message struct {
	Type      Message_Type               `protobuf:"varint,1,opt,name=type,enum=protos.Message_Type" json:"type,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Payload   []byte                     `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature []byte                     `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{12} }

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_UNDEFINED
}

func (m *Message) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Response struct {
	Status Response_StatusCode `protobuf:"varint,1,opt,name=status,enum=protos.Response_StatusCode" json:"status,omitempty"`
	Msg    []byte              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{13} }

func (m *Response) GetStatus() Response_StatusCode {
	if m != nil {
		return m.Status
	}
	return Response_UNDEFINED
}

func (m *Response) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "protos.Transaction")
	proto.RegisterType((*TransactionBlock)(nil), "protos.TransactionBlock")
	proto.RegisterType((*TransactionResult)(nil), "protos.TransactionResult")
	proto.RegisterType((*Block)(nil), "protos.Block")
	proto.RegisterType((*BlockchainInfo)(nil), "protos.BlockchainInfo")
	proto.RegisterType((*NonHashData)(nil), "protos.NonHashData")
	proto.RegisterType((*PeerAddress)(nil), "protos.PeerAddress")
	proto.RegisterType((*PeerID)(nil), "protos.PeerID")
	proto.RegisterType((*PeerEndpoint)(nil), "protos.PeerEndpoint")
	proto.RegisterType((*PeersMessage)(nil), "protos.PeersMessage")
	proto.RegisterType((*PeersAddresses)(nil), "protos.PeersAddresses")
	proto.RegisterType((*HelloMessage)(nil), "protos.HelloMessage")
	proto.RegisterType((*Message)(nil), "protos.Message")
	proto.RegisterType((*Response)(nil), "protos.Response")
	proto.RegisterEnum("protos.Transaction_Type", Transaction_Type_name, Transaction_Type_value)
	proto.RegisterEnum("protos.PeerEndpoint_Type", PeerEndpoint_Type_name, PeerEndpoint_Type_value)
	proto.RegisterEnum("protos.Message_Type", Message_Type_name, Message_Type_value)
	proto.RegisterEnum("protos.Response_StatusCode", Response_StatusCode_name, Response_StatusCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Peer service

type PeerClient interface {
	// Accepts a stream of Message during chat session, while receiving
	// other Message (e.g. from other peers).
	Chat(ctx context.Context, opts ...grpc.CallOption) (Peer_ChatClient, error)
	// Process a transaction from a remote source.
	ProcessTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Response, error)
}

type peerClient struct {
	cc *grpc.ClientConn
}

func NewPeerClient(cc *grpc.ClientConn) PeerClient {
	return &peerClient{cc}
}

func (c *peerClient) Chat(ctx context.Context, opts ...grpc.CallOption) (Peer_ChatClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Peer_serviceDesc.Streams[0], c.cc, "/protos.Peer/Chat", opts...)
	if err != nil {
		return nil, err
	}
	x := &peerChatClient{stream}
	return x, nil
}

type Peer_ChatClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type peerChatClient struct {
	grpc.ClientStream
}

func (x *peerChatClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *peerChatClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *peerClient) ProcessTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Peer/ProcessTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Peer service

type PeerServer interface {
	// Accepts a stream of Message during chat session, while receiving
	// other Message (e.g. from other peers).
	Chat(Peer_ChatServer) error
	// Process a transaction from a remote source.
	ProcessTransaction(context.Context, *Transaction) (*Response, error)
}

func RegisterPeerServer(s *grpc.Server, srv PeerServer) {
	s.RegisterService(&_Peer_serviceDesc, srv)
}

func _Peer_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PeerServer).Chat(&peerChatServer{stream})
}

type Peer_ChatServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type peerChatServer struct {
	grpc.ServerStream
}

func (x *peerChatServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *peerChatServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Peer_ProcessTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServer).ProcessTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Peer/ProcessTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServer).ProcessTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _Peer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Peer",
	HandlerType: (*PeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessTransaction",
			Handler:    _Peer_ProcessTransaction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _Peer_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "fabric.proto",
}

func init() { proto.RegisterFile("fabric.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 1249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0xae, 0xfc, 0x93, 0xc4, 0xc7, 0x8e, 0xa3, 0xb0, 0x6e, 0xab, 0xba, 0x45, 0x67, 0xe8, 0x62,
	0x30, 0x8a, 0xce, 0x1d, 0x52, 0x14, 0x2d, 0x06, 0x6c, 0x98, 0x2b, 0xa9, 0x8d, 0x50, 0x47, 0xf6,
	0x28, 0x25, 0x43, 0x77, 0x13, 0xa8, 0x32, 0xe3, 0x08, 0xb5, 0x45, 0x41, 0xa4, 0x83, 0xe5, 0x76,
	0x97, 0x7b, 0x95, 0x5d, 0xee, 0x1d, 0xb6, 0x3d, 0xc2, 0x80, 0x3d, 0xc4, 0x6e, 0xf6, 0x00, 0x03,
	0x29, 0xc9, 0x92, 0x5d, 0xb7, 0xfb, 0xb9, 0x49, 0x78, 0xbe, 0xf3, 0x91, 0x3c, 0x3f, 0x9f, 0x78,
	0x0c, 0xad, 0x0b, 0xff, 0x6d, 0x12, 0x06, 0x83, 0x38, 0xa1, 0x9c, 0xa2, 0x1d, 0xf9, 0x8f, 0x75,
	0x0f, 0x82, 0x4b, 0x3f, 0x8c, 0x02, 0x3a, 0x25, 0xa9, 0xa3, 0xdb, 0x59, 0x01, 0xe4, 0x8a, 0x44,
	0x3c, 0x43, 0x3f, 0x99, 0x51, 0x3a, 0x9b, 0x93, 0xc7, 0xd2, 0x7a, 0xbb, 0xbc, 0x78, 0xcc, 0xc3,
	0x05, 0x61, 0xdc, 0x5f, 0xc4, 0x29, 0x41, 0xff, 0xbd, 0x06, 0x4d, 0x2f, 0xf1, 0x23, 0xe6, 0x07,
	0x3c, 0xa4, 0x11, 0x7a, 0x04, 0x35, 0x7e, 0x1d, 0x13, 0x4d, 0xe9, 0x29, 0xfd, 0xf6, 0x91, 0x96,
	0xb2, 0xd8, 0xa0, 0x44, 0x19, 0x78, 0xd7, 0x31, 0xc1, 0x92, 0x85, 0x7a, 0xd0, 0x5c, 0x5d, 0x6b,
	0x9b, 0x5a, 0xa5, 0xa7, 0xf4, 0x5b, 0xb8, 0x0c, 0x21, 0x0d, 0x76, 0x63, 0xff, 0x7a, 0x4e, 0xfd,
	0xa9, 0x56, 0x95, 0xde, 0xdc, 0x44, 0x5d, 0xd8, 0x5b, 0x10, 0xee, 0x4f, 0x7d, 0xee, 0x6b, 0x35,
	0xe9, 0x5a, 0xd9, 0x08, 0x41, 0x8d, 0x7f, 0x1f, 0x4e, 0xb5, 0x7a, 0x4f, 0xe9, 0x37, 0xb0, 0x5c,
	0xa3, 0xe7, 0xd0, 0x58, 0x05, 0xaf, 0xed, 0xf4, 0x94, 0x7e, 0xf3, 0xa8, 0x3b, 0x48, 0xd3, 0x1b,
	0xe4, 0xe9, 0x0d, 0xbc, 0x9c, 0x81, 0x0b, 0x32, 0x9a, 0x40, 0x27, 0xa0, 0xd1, 0x45, 0x38, 0x25,
	0x11, 0x0f, 0xfd, 0x79, 0xc8, 0xaf, 0x47, 0xe4, 0x8a, 0xcc, 0xb5, 0x5d, 0x99, 0xe3, 0xfd, 0x3c,
	0x47, 0x63, 0x0b, 0x07, 0x6f, 0xdd, 0x89, 0x5e, 0xc2, 0x83, 0x0d, 0x7c, 0x22, 0xce, 0x08, 0xe8,
	0xfc, 0x8c, 0x24, 0x2c, 0xa4, 0x91, 0xb6, 0x27, 0x23, 0xff, 0x07, 0x16, 0xea, 0x40, 0x3d, 0xa2,
	0x51, 0x40, 0xb4, 0x86, 0x2c, 0x40, 0x6a, 0x20, 0x1d, 0x5a, 0x9c, 0x9e, 0xf9, 0xf3, 0x70, 0xea,
	0x73, 0x9a, 0x30, 0x0d, 0xa4, 0x73, 0x0d, 0x13, 0x15, 0x0a, 0x48, 0xc2, 0xb5, 0xa6, 0xf4, 0xc9,
	0x35, 0xba, 0x0f, 0x0d, 0x16, 0xce, 0x22, 0x9f, 0x2f, 0x13, 0xa2, 0xb5, 0xa4, 0xa3, 0x00, 0x74,
	0x0a, 0x35, 0xd1, 0x39, 0xb4, 0x0f, 0x8d, 0x53, 0xc7, 0xb4, 0x5e, 0xda, 0x8e, 0x65, 0xaa, 0x37,
	0x50, 0x07, 0x54, 0xe3, 0x78, 0x68, 0x3b, 0xc6, 0xd8, 0xb4, 0xce, 0x4d, 0x6b, 0x32, 0x1a, 0xbf,
	0x51, 0x95, 0x75, 0xd4, 0x76, 0xce, 0xc6, 0xaf, 0x2d, 0xb5, 0x82, 0x6e, 0xc2, 0x41, 0x81, 0x7e,
	0x73, 0x6a, 0xe1, 0x37, 0x6a, 0x15, 0xdd, 0x81, 0x9b, 0x05, 0xe8, 0x59, 0xf8, 0xc4, 0x76, 0x86,
	0x9e, 0xa5, 0xd6, 0xf4, 0xd7, 0xa0, 0x96, 0x64, 0xf3, 0x62, 0x4e, 0x83, 0x77, 0xe8, 0x19, 0xb4,
	0x78, 0x81, 0x31, 0x4d, 0xe9, 0x55, 0xfb, 0xcd, 0xa3, 0x9b, 0x5b, 0x64, 0x86, 0xd7, 0x88, 0xfa,
	0xcf, 0x0a, 0x1c, 0x96, 0xbd, 0x84, 0x2d, 0xe7, 0x7c, 0xa5, 0x13, 0xa5, 0xa4, 0x93, 0xdb, 0xb0,
	0x93, 0x48, 0x6f, 0x26, 0xc7, 0xcc, 0x12, 0xd5, 0x21, 0x49, 0x42, 0x13, 0x83, 0x4e, 0x89, 0xd4,
	0xe2, 0x3e, 0x2e, 0x00, 0xd1, 0x09, 0x69, 0x48, 0x29, 0x36, 0x70, 0x6a, 0xa0, 0xaf, 0xa0, 0xbd,
	0x12, 0xb3, 0x25, 0x3e, 0x2b, 0xa9, 0xc8, 0xe6, 0xd1, 0xed, 0x95, 0x66, 0xd6, 0xbc, 0x78, 0x83,
	0xad, 0xff, 0x51, 0x81, 0x7a, 0x9a, 0xb8, 0x06, 0xbb, 0x57, 0x99, 0x34, 0x14, 0x79, 0x77, 0x6e,
	0xae, 0xeb, 0xba, 0xf2, 0x5f, 0x74, 0xbd, 0x59, 0xcc, 0xea, 0xbf, 0x2c, 0xa6, 0x14, 0x0a, 0xf7,
	0x39, 0x39, 0xf6, 0xd9, 0x65, 0xf6, 0xed, 0x15, 0x00, 0x7a, 0x04, 0x87, 0x71, 0x42, 0xae, 0x42,
	0xba, 0x64, 0x32, 0x76, 0xc9, 0xaa, 0x4b, 0xd6, 0xfb, 0x0e, 0xc1, 0x0e, 0x68, 0xc4, 0x48, 0xc4,
	0x96, 0xec, 0x24, 0xff, 0x9e, 0x77, 0x52, 0xf6, 0x7b, 0x0e, 0xf4, 0x14, 0x9a, 0x11, 0x8d, 0xc4,
	0x46, 0x53, 0xf0, 0x76, 0x65, 0xba, 0xab, 0x88, 0x9d, 0xc2, 0x85, 0xcb, 0x3c, 0xd1, 0x1d, 0xd1,
	0x5b, 0xa6, 0xed, 0xf5, 0xaa, 0xa2, 0x3b, 0xd2, 0xd0, 0x7f, 0x50, 0xa0, 0x2d, 0x03, 0x91, 0x55,
	0xb7, 0xa3, 0x0b, 0x2a, 0x9a, 0x7f, 0x49, 0xc2, 0xd9, 0x25, 0x97, 0x55, 0xae, 0xe1, 0xcc, 0x42,
	0x0f, 0x41, 0x0d, 0x96, 0x49, 0x42, 0x22, 0x5e, 0xa4, 0x94, 0xca, 0xe3, 0x3d, 0x7c, 0x7b, 0xfe,
	0xd5, 0x0f, 0xe4, 0xaf, 0xff, 0xa4, 0x40, 0xb3, 0x14, 0x37, 0xfa, 0x0e, 0xba, 0x73, 0x1a, 0xf8,
	0xf3, 0x11, 0x99, 0xce, 0x48, 0x62, 0xd0, 0xc5, 0x22, 0xe4, 0xab, 0xee, 0xc9, 0xa8, 0x3e, 0xde,
	0xdf, 0x8f, 0xec, 0x46, 0x5f, 0xc3, 0xc1, 0xba, 0xc0, 0x98, 0x56, 0x91, 0x3d, 0xff, 0x90, 0x1e,
	0x37, 0xe9, 0xfa, 0x53, 0x68, 0x4e, 0x08, 0x49, 0x86, 0xd3, 0x69, 0x42, 0x98, 0x7c, 0x45, 0x2e,
	0x29, 0xe3, 0xf9, 0xf7, 0x23, 0xd6, 0x02, 0x8b, 0x69, 0x92, 0x7e, 0x3d, 0x75, 0x2c, 0xd7, 0xfa,
	0x7d, 0xd8, 0x11, 0xdb, 0x6c, 0x53, 0x78, 0x23, 0x7f, 0x41, 0xf2, 0x1d, 0x62, 0xad, 0xff, 0xa2,
	0x40, 0x4b, 0xb8, 0xad, 0x68, 0x1a, 0xd3, 0x30, 0xe2, 0xe8, 0x01, 0x54, 0x6c, 0x33, 0xcb, 0xb5,
	0x9d, 0x87, 0x96, 0x1e, 0x80, 0x2b, 0xe9, 0x50, 0xf0, 0xd3, 0x08, 0xe4, 0x2d, 0x0d, 0x9c, 0x9b,
	0xe8, 0xb3, 0x6c, 0xfc, 0x54, 0xe5, 0xd3, 0x7c, 0xb7, 0xbc, 0x37, 0x3f, 0xbd, 0x3c, 0x7f, 0x3a,
	0x50, 0x8f, 0xdf, 0x85, 0xb6, 0x99, 0x89, 0x38, 0x35, 0xf4, 0x67, 0xdb, 0x5f, 0xba, 0x7d, 0x68,
	0x9c, 0x0d, 0x47, 0xb6, 0x39, 0xf4, 0xc6, 0x58, 0x55, 0xd0, 0x21, 0xec, 0x3b, 0x63, 0xe7, 0xbc,
	0x80, 0x2a, 0xfa, 0x17, 0x69, 0x1e, 0xec, 0x84, 0x30, 0xe6, 0xcf, 0x08, 0x7a, 0x08, 0xf5, 0x58,
	0xd8, 0xd9, 0x33, 0xd5, 0xd9, 0x16, 0x0e, 0x4e, 0x29, 0xfa, 0x00, 0xda, 0x72, 0x6f, 0x56, 0x5a,
	0x22, 0xbf, 0x32, 0x3f, 0x37, 0xe4, 0x09, 0x0d, 0x5c, 0x00, 0x7a, 0x0c, 0xad, 0x63, 0x32, 0x9f,
	0xd3, 0xfc, 0xae, 0xe7, 0xd0, 0x8a, 0x4b, 0xc7, 0x66, 0xd5, 0xdb, 0x7e, 0xe5, 0x1a, 0x13, 0x7d,
	0x0a, 0x6d, 0x61, 0x1b, 0x09, 0xc9, 0x06, 0x4d, 0x26, 0xd6, 0x0d, 0x54, 0xff, 0xb3, 0x0a, 0xbb,
	0xf9, 0x6d, 0xfd, 0xb5, 0x31, 0xbf, 0xba, 0x25, 0x73, 0x97, 0x4b, 0xfc, 0xff, 0x9f, 0xa7, 0x0f,
	0x8f, 0xfe, 0xb5, 0x41, 0x55, 0xdb, 0x1c, 0x54, 0xbf, 0x56, 0xb6, 0xf7, 0xaf, 0x0d, 0x60, 0xda,
	0xae, 0x71, 0x7e, 0x6c, 0x8d, 0x46, 0x63, 0x55, 0x11, 0xd3, 0x48, 0xda, 0xe2, 0xcf, 0xd8, 0x71,
	0x2c, 0xc3, 0x53, 0x2b, 0x08, 0x41, 0x5b, 0x82, 0xaf, 0x2c, 0xef, 0x7c, 0x62, 0x59, 0xd8, 0x55,
	0xab, 0xab, 0x8d, 0xa9, 0x5d, 0x43, 0x07, 0xd0, 0x94, 0xb6, 0x63, 0x7d, 0x7b, 0xe2, 0xbe, 0x52,
	0xeb, 0xe8, 0x16, 0x1c, 0xca, 0x11, 0x76, 0xee, 0xe1, 0xa1, 0xe3, 0x0e, 0x0d, 0xcf, 0x1e, 0x3b,
	0xea, 0x8e, 0xb8, 0xc0, 0x7d, 0xe3, 0xa4, 0x67, 0xbd, 0x18, 0x8d, 0x8d, 0xd7, 0xae, 0xda, 0x14,
	0x9b, 0x25, 0x98, 0x01, 0x2d, 0x31, 0x2a, 0x0b, 0xe0, 0x7c, 0x68, 0x9a, 0x96, 0xa9, 0xee, 0xa3,
	0x7b, 0x70, 0x47, 0xa2, 0xae, 0x37, 0xf4, 0x2c, 0x79, 0x82, 0xeb, 0x0c, 0x27, 0xee, 0xf1, 0xd8,
	0x53, 0xdb, 0x62, 0x64, 0x96, 0x9c, 0x2b, 0xc7, 0x01, 0xba, 0x0b, 0xb7, 0x36, 0x76, 0x99, 0xd6,
	0xc8, 0x1b, 0xba, 0xaa, 0x2a, 0x62, 0x2c, 0xb9, 0x32, 0xf8, 0x10, 0xb5, 0x60, 0x0f, 0x5b, 0xee,
	0x64, 0xec, 0xb8, 0x96, 0xda, 0x11, 0x15, 0x33, 0xc4, 0xd2, 0x71, 0x4f, 0x5d, 0xf5, 0x96, 0xfe,
	0xa3, 0x02, 0x7b, 0x98, 0xb0, 0x58, 0x3c, 0xc3, 0xe8, 0x09, 0xec, 0x88, 0x37, 0x7e, 0xc9, 0xb2,
	0xa6, 0xdf, 0xcb, 0x9b, 0x9e, 0x33, 0x06, 0xae, 0x74, 0x8b, 0x71, 0x88, 0x33, 0x2a, 0x52, 0xa1,
	0xba, 0x60, 0xb3, 0xec, 0xa9, 0x14, 0x4b, 0xfd, 0x19, 0x40, 0xc1, 0xdb, 0x6c, 0x51, 0x0b, 0x76,
	0xdd, 0x53, 0xc3, 0xb0, 0x5c, 0x57, 0xfd, 0x4d, 0x11, 0xd6, 0xcb, 0xa1, 0x3d, 0x3a, 0xc5, 0x96,
	0xfa, 0x57, 0xf5, 0x68, 0x09, 0x35, 0x21, 0x62, 0x34, 0x80, 0x9a, 0x71, 0xe9, 0x73, 0x74, 0xb0,
	0x21, 0xba, 0xee, 0x26, 0xa0, 0xdf, 0xe8, 0x2b, 0x9f, 0x2b, 0xe8, 0x4b, 0x40, 0x93, 0x84, 0x06,
	0x84, 0xb1, 0xf2, 0xef, 0xd4, 0x6d, 0x53, 0xae, 0xab, 0x6e, 0xa6, 0xa4, 0xdf, 0x78, 0x9b, 0xfe,
	0x60, 0x7e, 0xf2, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x34, 0x75, 0x43, 0x47, 0x0b, 0x00,
	0x00,
}
