// Code generated by protoc-gen-go. DO NOT EDIT.
// source: subscriptiontx.proto

/*
Package ccprotos is a generated protocol buffer package.

It is generated from these files:
	subscriptiontx.proto

It has these top-level messages:
	RegContract
	QueryContract
	RedeemContract
	Contract
*/
package ccprotos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import protos "hyperledger.abchain.org/protos"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// user can register a public key only if it has own some pais
type RegContract struct {
	DelegatorAddr *protos.TxAddr        `protobuf:"bytes,1,opt,name=delegatorAddr" json:"delegatorAddr,omitempty"`
	ContractBody  []*RegContract_Member `protobuf:"bytes,5,rep,name=contractBody" json:"contractBody,omitempty"`
}

func (m *RegContract) Reset()                    { *m = RegContract{} }
func (m *RegContract) String() string            { return proto.CompactTextString(m) }
func (*RegContract) ProtoMessage()               {}
func (*RegContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegContract) GetDelegatorAddr() *protos.TxAddr {
	if m != nil {
		return m.DelegatorAddr
	}
	return nil
}

func (m *RegContract) GetContractBody() []*RegContract_Member {
	if m != nil {
		return m.ContractBody
	}
	return nil
}

type RegContract_Member struct {
	Addr   *protos.TxAddr `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Weight int32          `protobuf:"varint,2,opt,name=weight" json:"weight,omitempty"`
}

func (m *RegContract_Member) Reset()                    { *m = RegContract_Member{} }
func (m *RegContract_Member) String() string            { return proto.CompactTextString(m) }
func (*RegContract_Member) ProtoMessage()               {}
func (*RegContract_Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *RegContract_Member) GetAddr() *protos.TxAddr {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *RegContract_Member) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type QueryContract struct {
	ContractAddr *protos.TxAddr `protobuf:"bytes,1,opt,name=contractAddr" json:"contractAddr,omitempty"`
	MemberAddr   *protos.TxAddr `protobuf:"bytes,2,opt,name=memberAddr" json:"memberAddr,omitempty"`
}

func (m *QueryContract) Reset()                    { *m = QueryContract{} }
func (m *QueryContract) String() string            { return proto.CompactTextString(m) }
func (*QueryContract) ProtoMessage()               {}
func (*QueryContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QueryContract) GetContractAddr() *protos.TxAddr {
	if m != nil {
		return m.ContractAddr
	}
	return nil
}

func (m *QueryContract) GetMemberAddr() *protos.TxAddr {
	if m != nil {
		return m.MemberAddr
	}
	return nil
}

type RedeemContract struct {
	Contract *protos.TxAddr `protobuf:"bytes,1,opt,name=contract" json:"contract,omitempty"`
	Amount   []byte         `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	To       *protos.TxAddr `protobuf:"bytes,3,opt,name=to" json:"to,omitempty"`
	Redeem   *protos.TxAddr `protobuf:"bytes,4,opt,name=redeem" json:"redeem,omitempty"`
}

func (m *RedeemContract) Reset()                    { *m = RedeemContract{} }
func (m *RedeemContract) String() string            { return proto.CompactTextString(m) }
func (*RedeemContract) ProtoMessage()               {}
func (*RedeemContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RedeemContract) GetContract() *protos.TxAddr {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *RedeemContract) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *RedeemContract) GetTo() *protos.TxAddr {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *RedeemContract) GetRedeem() *protos.TxAddr {
	if m != nil {
		return m.Redeem
	}
	return nil
}

type Contract struct {
	DelegatorPkFingerPrint []byte                     `protobuf:"bytes,1,opt,name=delegatorPkFingerPrint,proto3" json:"delegatorPkFingerPrint,omitempty"`
	TotalRedeem            []byte                     `protobuf:"bytes,3,opt,name=totalRedeem,proto3" json:"totalRedeem,omitempty"`
	Status                 []*Contract_MemberStatus   `protobuf:"bytes,5,rep,name=status" json:"status,omitempty"`
	ContractTs             *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=contractTs" json:"contractTs,omitempty"`
	FrozenTo               *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=frozenTo" json:"frozenTo,omitempty"`
	IsFrozen               bool                       `protobuf:"varint,10,opt,name=isFrozen" json:"isFrozen,omitempty"`
	NextAddr               *protos.TxAddr             `protobuf:"bytes,12,opt,name=nextAddr" json:"nextAddr,omitempty"`
}

func (m *Contract) Reset()                    { *m = Contract{} }
func (m *Contract) String() string            { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()               {}
func (*Contract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Contract) GetDelegatorPkFingerPrint() []byte {
	if m != nil {
		return m.DelegatorPkFingerPrint
	}
	return nil
}

func (m *Contract) GetTotalRedeem() []byte {
	if m != nil {
		return m.TotalRedeem
	}
	return nil
}

func (m *Contract) GetStatus() []*Contract_MemberStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Contract) GetContractTs() *google_protobuf.Timestamp {
	if m != nil {
		return m.ContractTs
	}
	return nil
}

func (m *Contract) GetFrozenTo() *google_protobuf.Timestamp {
	if m != nil {
		return m.FrozenTo
	}
	return nil
}

func (m *Contract) GetIsFrozen() bool {
	if m != nil {
		return m.IsFrozen
	}
	return false
}

func (m *Contract) GetNextAddr() *protos.TxAddr {
	if m != nil {
		return m.NextAddr
	}
	return nil
}

type Contract_MemberStatus struct {
	Weight      int32  `protobuf:"varint,2,opt,name=weight" json:"weight,omitempty"`
	TotalRedeem []byte `protobuf:"bytes,3,opt,name=totalRedeem,proto3" json:"totalRedeem,omitempty"`
	MemberID    string `protobuf:"bytes,5,opt,name=memberID" json:"memberID,omitempty"`
}

func (m *Contract_MemberStatus) Reset()                    { *m = Contract_MemberStatus{} }
func (m *Contract_MemberStatus) String() string            { return proto.CompactTextString(m) }
func (*Contract_MemberStatus) ProtoMessage()               {}
func (*Contract_MemberStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *Contract_MemberStatus) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Contract_MemberStatus) GetTotalRedeem() []byte {
	if m != nil {
		return m.TotalRedeem
	}
	return nil
}

func (m *Contract_MemberStatus) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func init() {
	proto.RegisterType((*RegContract)(nil), "ccprotos.RegContract")
	proto.RegisterType((*RegContract_Member)(nil), "ccprotos.RegContract.Member")
	proto.RegisterType((*QueryContract)(nil), "ccprotos.QueryContract")
	proto.RegisterType((*RedeemContract)(nil), "ccprotos.RedeemContract")
	proto.RegisterType((*Contract)(nil), "ccprotos.Contract")
	proto.RegisterType((*Contract_MemberStatus)(nil), "ccprotos.Contract.MemberStatus")
}

func init() { proto.RegisterFile("subscriptiontx.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0x26, 0xed, 0x36, 0xc4, 0xd3, 0xec, 0x5e, 0x0c, 0xb2, 0x84, 0x20, 0x6e, 0xe8, 0x85, 0x04,
	0x85, 0x29, 0x54, 0x59, 0xc1, 0x2b, 0x7f, 0x96, 0x05, 0x2f, 0x84, 0x75, 0xec, 0x0b, 0x4c, 0x32,
	0x67, 0xd3, 0x60, 0x93, 0x29, 0x33, 0x13, 0x6c, 0x7d, 0x16, 0xdf, 0xc5, 0x07, 0xf0, 0xa5, 0xa4,
	0x33, 0x49, 0x36, 0x95, 0x56, 0xbd, 0xcb, 0x39, 0xdf, 0x77, 0x72, 0xce, 0x37, 0xdf, 0x07, 0x8f,
	0x75, 0x93, 0xe9, 0x5c, 0x95, 0x1b, 0x53, 0xca, 0xda, 0x6c, 0xe9, 0x46, 0x49, 0x23, 0x49, 0x90,
	0xe7, 0xf6, 0x43, 0xc7, 0x2f, 0x56, 0xbb, 0x0d, 0xaa, 0x35, 0x8a, 0x02, 0x15, 0xe5, 0x59, 0xbe,
	0xe2, 0x65, 0x4d, 0xa5, 0x2a, 0xe6, 0x0e, 0x9f, 0x9b, 0x2d, 0x17, 0x42, 0xb9, 0xb1, 0xf8, 0xaa,
	0x90, 0xb2, 0x58, 0xa3, 0xc3, 0xb2, 0xe6, 0x7e, 0x6e, 0xca, 0x0a, 0xb5, 0xe1, 0xd5, 0xc6, 0x11,
	0x66, 0xbf, 0x3c, 0x98, 0x32, 0x2c, 0x3e, 0xc8, 0xda, 0x28, 0x9e, 0x1b, 0xf2, 0x0a, 0xce, 0x05,
	0xae, 0xb1, 0xe0, 0x46, 0xaa, 0x77, 0x42, 0xa8, 0xc8, 0x4b, 0xbc, 0x74, 0xba, 0xb8, 0x70, 0x74,
	0x4d, 0x97, 0xdb, 0x7d, 0x97, 0x1d, 0x92, 0xc8, 0x5b, 0x08, 0xf3, 0xf6, 0x0f, 0xef, 0xa5, 0xd8,
	0x45, 0x93, 0x64, 0x9c, 0x4e, 0x17, 0x4f, 0x68, 0x77, 0x34, 0x1d, 0xac, 0xa0, 0x9f, 0xb0, 0xca,
	0x50, 0xb1, 0x83, 0x89, 0xf8, 0x06, 0x7c, 0xd7, 0x27, 0x33, 0x38, 0xe3, 0xa7, 0x17, 0x5b, 0x8c,
	0x5c, 0x82, 0xff, 0x0d, 0xcb, 0x62, 0x65, 0xa2, 0x51, 0xe2, 0xa5, 0x13, 0xd6, 0x56, 0x33, 0x0d,
	0xe7, 0x9f, 0x1b, 0x54, 0xbb, 0x5e, 0xce, 0xe2, 0xe1, 0xb0, 0xbf, 0xa8, 0x39, 0xe0, 0x10, 0x0a,
	0x50, 0xd9, 0x53, 0xec, 0xc4, 0xe8, 0xe8, 0xc4, 0x80, 0x31, 0xfb, 0xe1, 0xc1, 0x05, 0x43, 0x81,
	0x58, 0xf5, 0x6b, 0x9f, 0x43, 0xd0, 0xfd, 0xf2, 0xc4, 0xca, 0x1e, 0xdf, 0x6b, 0xe1, 0x95, 0x6c,
	0x6a, 0xa7, 0x25, 0x64, 0x6d, 0x45, 0x9e, 0xc2, 0xc8, 0xc8, 0x68, 0x7c, 0x74, 0x7a, 0x64, 0x24,
	0x79, 0x06, 0xbe, 0xb2, 0x5b, 0xa3, 0xb3, 0xa3, 0x9c, 0x16, 0x9d, 0xfd, 0x1c, 0x43, 0xd0, 0x1f,
	0x76, 0x0d, 0x97, 0xbd, 0x73, 0x77, 0x5f, 0x6f, 0xcb, 0xba, 0x40, 0x75, 0xa7, 0xca, 0xda, 0x9d,
	0x19, 0xb2, 0x13, 0x28, 0x49, 0x60, 0x6a, 0xa4, 0xe1, 0x6b, 0xa7, 0xd3, 0x5e, 0x15, 0xb2, 0x61,
	0x8b, 0xbc, 0x06, 0x5f, 0x1b, 0x6e, 0x1a, 0xdd, 0x9a, 0x7f, 0xf5, 0x60, 0xfe, 0x1f, 0xce, 0x7f,
	0xb1, 0x34, 0xd6, 0xd2, 0xc9, 0x1b, 0x80, 0xee, 0x2d, 0x96, 0x3a, 0xf2, 0xad, 0x96, 0x98, 0xba,
	0xdc, 0xd2, 0x2e, 0xb7, 0x74, 0xd9, 0xe5, 0x96, 0x0d, 0xd8, 0xe4, 0x1a, 0x82, 0x7b, 0x25, 0xbf,
	0x63, 0xbd, 0x94, 0x51, 0xf0, 0xcf, 0xc9, 0x9e, 0x4b, 0x62, 0x08, 0x4a, 0x7d, 0x6b, 0xab, 0x08,
	0x12, 0x2f, 0x0d, 0x58, 0x5f, 0xef, 0xbd, 0xab, 0x71, 0xeb, 0xe2, 0x12, 0x1e, 0xf7, 0xae, 0xc3,
	0x63, 0x01, 0xe1, 0x50, 0xd3, 0xa9, 0x5c, 0xfe, 0xc7, 0xf3, 0xc5, 0x10, 0xb8, 0x48, 0x7d, 0xbc,
	0x89, 0x26, 0x89, 0x97, 0x3e, 0x62, 0x7d, 0x9d, 0xf9, 0x76, 0xfd, 0xcb, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x81, 0x06, 0x71, 0x46, 0x1a, 0x04, 0x00, 0x00,
}
