// Code generated by protoc-gen-go. DO NOT EDIT.
// source: subscriptiontx.proto

package ccprotos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import protos1 "hyperledger.abchain.org/protos"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// user can register a public key only if it has own some pais
type RegContract struct {
	DelegatorAddr *protos1.TxAddr       `protobuf:"bytes,1,opt,name=delegatorAddr" json:"delegatorAddr,omitempty"`
	ContractBody  []*RegContract_Member `protobuf:"bytes,5,rep,name=contractBody" json:"contractBody,omitempty"`
}

func (m *RegContract) Reset()                    { *m = RegContract{} }
func (m *RegContract) String() string            { return proto.CompactTextString(m) }
func (*RegContract) ProtoMessage()               {}
func (*RegContract) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *RegContract) GetDelegatorAddr() *protos1.TxAddr {
	if m != nil {
		return m.DelegatorAddr
	}
	return nil
}

func (m *RegContract) GetContractBody() []*RegContract_Member {
	if m != nil {
		return m.ContractBody
	}
	return nil
}

type RegContract_Member struct {
	Addr   *protos1.TxAddr `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Weight uint32          `protobuf:"varint,2,opt,name=weight" json:"weight,omitempty"`
}

func (m *RegContract_Member) Reset()                    { *m = RegContract_Member{} }
func (m *RegContract_Member) String() string            { return proto.CompactTextString(m) }
func (*RegContract_Member) ProtoMessage()               {}
func (*RegContract_Member) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

func (m *RegContract_Member) GetAddr() *protos1.TxAddr {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *RegContract_Member) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type QueryContract struct {
	ContractAddr *protos1.TxAddr `protobuf:"bytes,1,opt,name=contractAddr" json:"contractAddr,omitempty"`
	MemberAddr   *protos1.TxAddr `protobuf:"bytes,2,opt,name=memberAddr" json:"memberAddr,omitempty"`
}

func (m *QueryContract) Reset()                    { *m = QueryContract{} }
func (m *QueryContract) String() string            { return proto.CompactTextString(m) }
func (*QueryContract) ProtoMessage()               {}
func (*QueryContract) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *QueryContract) GetContractAddr() *protos1.TxAddr {
	if m != nil {
		return m.ContractAddr
	}
	return nil
}

func (m *QueryContract) GetMemberAddr() *protos1.TxAddr {
	if m != nil {
		return m.MemberAddr
	}
	return nil
}

type RedeemContract struct {
	Contract *protos1.TxAddr `protobuf:"bytes,1,opt,name=contract" json:"contract,omitempty"`
	Amount   []byte          `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	To       *protos1.TxAddr `protobuf:"bytes,3,opt,name=to" json:"to,omitempty"`
	Redeem   *protos1.TxAddr `protobuf:"bytes,4,opt,name=redeem" json:"redeem,omitempty"`
}

func (m *RedeemContract) Reset()                    { *m = RedeemContract{} }
func (m *RedeemContract) String() string            { return proto.CompactTextString(m) }
func (*RedeemContract) ProtoMessage()               {}
func (*RedeemContract) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *RedeemContract) GetContract() *protos1.TxAddr {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *RedeemContract) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *RedeemContract) GetTo() *protos1.TxAddr {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *RedeemContract) GetRedeem() *protos1.TxAddr {
	if m != nil {
		return m.Redeem
	}
	return nil
}

func init() {
	proto.RegisterType((*RegContract)(nil), "ccprotos.RegContract")
	proto.RegisterType((*RegContract_Member)(nil), "ccprotos.RegContract.Member")
	proto.RegisterType((*QueryContract)(nil), "ccprotos.QueryContract")
	proto.RegisterType((*RedeemContract)(nil), "ccprotos.RedeemContract")
}

func init() { proto.RegisterFile("subscriptiontx.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x4f, 0x5b, 0x4a, 0xc3, 0x40,
	0x14, 0x25, 0x69, 0x0d, 0xe5, 0xf6, 0xf1, 0x31, 0x88, 0x84, 0x22, 0x52, 0xf2, 0x21, 0x45, 0x61,
	0x0a, 0xd5, 0x05, 0xf8, 0xfa, 0xf5, 0xc3, 0xc1, 0x0d, 0x4c, 0x66, 0x2e, 0x69, 0xa0, 0xc9, 0x94,
	0x9b, 0x29, 0x26, 0x7b, 0x71, 0x47, 0x6e, 0x4a, 0x3a, 0x49, 0x63, 0x03, 0xa9, 0x7f, 0x33, 0xe7,
	0x71, 0xcf, 0x39, 0x70, 0x59, 0xec, 0xe3, 0x42, 0x51, 0xba, 0xb3, 0xa9, 0xc9, 0x6d, 0xc9, 0x77,
	0x64, 0xac, 0x61, 0x23, 0xa5, 0xdc, 0xa3, 0x98, 0xdf, 0x6f, 0xaa, 0x1d, 0xd2, 0x16, 0x75, 0x82,
	0xc4, 0x65, 0xac, 0x36, 0x32, 0xcd, 0xb9, 0xa1, 0x64, 0x55, 0xf3, 0x2b, 0x5b, 0x4a, 0xad, 0xa9,
	0xb6, 0x45, 0x3f, 0x1e, 0x8c, 0x05, 0x26, 0xaf, 0x26, 0xb7, 0x24, 0x95, 0x65, 0x8f, 0x30, 0xd5,
	0xb8, 0xc5, 0x44, 0x5a, 0x43, 0xcf, 0x5a, 0x53, 0xe8, 0x2d, 0xbc, 0xe5, 0x78, 0x3d, 0xab, 0xe5,
	0x05, 0xff, 0x2c, 0x0f, 0xa8, 0xe8, 0x8a, 0xd8, 0x13, 0x4c, 0x54, 0x73, 0xe1, 0xc5, 0xe8, 0x2a,
	0xbc, 0x58, 0x0c, 0x96, 0xe3, 0xf5, 0x35, 0x3f, 0x76, 0xe2, 0x27, 0x11, 0xfc, 0x1d, 0xb3, 0x18,
	0x49, 0x74, 0x1c, 0xf3, 0x37, 0x08, 0x6a, 0x9c, 0x45, 0x30, 0x94, 0xe7, 0x83, 0x1d, 0xc7, 0xae,
	0x20, 0xf8, 0xc2, 0x34, 0xd9, 0xd8, 0xd0, 0x5f, 0x78, 0xcb, 0xa9, 0x68, 0x7e, 0x51, 0x01, 0xd3,
	0x8f, 0x3d, 0x52, 0xd5, 0xce, 0x59, 0xff, 0x15, 0xfb, 0x67, 0x4d, 0x47, 0xc3, 0x38, 0x40, 0xe6,
	0xaa, 0x38, 0x87, 0xdf, 0xeb, 0x38, 0x51, 0x44, 0xdf, 0x1e, 0xcc, 0x04, 0x6a, 0xc4, 0xac, 0x8d,
	0xbd, 0x83, 0xd1, 0xf1, 0xe4, 0x99, 0xc8, 0x96, 0x3f, 0x6c, 0x91, 0x99, 0xd9, 0xe7, 0xf5, 0x96,
	0x89, 0x68, 0x7e, 0xec, 0x06, 0x7c, 0x6b, 0xc2, 0x41, 0xaf, 0xdb, 0xb7, 0x86, 0xdd, 0x42, 0x40,
	0x2e, 0x35, 0x1c, 0xf6, 0x6a, 0x1a, 0x36, 0x0e, 0x1c, 0xfc, 0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0xb0, 0x92, 0xd3, 0x5f, 0x37, 0x02, 0x00, 0x00,
}
