// Code generated by protoc-gen-go. DO NOT EDIT.
// source: subscriptiontx.proto

package ccshareprotos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protos "hyperledger.abchain.org/protos"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//user can register a public key only if it has own some pais
type RegContract struct {
	Delegator            *protos.TxAddr        `protobuf:"bytes,4,opt,name=delegator,proto3" json:"delegator,omitempty"`
	ContractBody         []*RegContract_Member `protobuf:"bytes,5,rep,name=contractBody,proto3" json:"contractBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RegContract) Reset()         { *m = RegContract{} }
func (m *RegContract) String() string { return proto.CompactTextString(m) }
func (*RegContract) ProtoMessage()    {}
func (*RegContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2978edb3d9b2dbe, []int{0}
}

func (m *RegContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegContract.Unmarshal(m, b)
}
func (m *RegContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegContract.Marshal(b, m, deterministic)
}
func (m *RegContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegContract.Merge(m, src)
}
func (m *RegContract) XXX_Size() int {
	return xxx_messageInfo_RegContract.Size(m)
}
func (m *RegContract) XXX_DiscardUnknown() {
	xxx_messageInfo_RegContract.DiscardUnknown(m)
}

var xxx_messageInfo_RegContract proto.InternalMessageInfo

func (m *RegContract) GetDelegator() *protos.TxAddr {
	if m != nil {
		return m.Delegator
	}
	return nil
}

func (m *RegContract) GetContractBody() []*RegContract_Member {
	if m != nil {
		return m.ContractBody
	}
	return nil
}

type RegContract_Member struct {
	Addr                 *protos.TxAddr `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Weight               int32          `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RegContract_Member) Reset()         { *m = RegContract_Member{} }
func (m *RegContract_Member) String() string { return proto.CompactTextString(m) }
func (*RegContract_Member) ProtoMessage()    {}
func (*RegContract_Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2978edb3d9b2dbe, []int{0, 0}
}

func (m *RegContract_Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegContract_Member.Unmarshal(m, b)
}
func (m *RegContract_Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegContract_Member.Marshal(b, m, deterministic)
}
func (m *RegContract_Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegContract_Member.Merge(m, src)
}
func (m *RegContract_Member) XXX_Size() int {
	return xxx_messageInfo_RegContract_Member.Size(m)
}
func (m *RegContract_Member) XXX_DiscardUnknown() {
	xxx_messageInfo_RegContract_Member.DiscardUnknown(m)
}

var xxx_messageInfo_RegContract_Member proto.InternalMessageInfo

func (m *RegContract_Member) GetAddr() *protos.TxAddr {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *RegContract_Member) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type QueryContract struct {
	ContractAddr         *protos.TxAddr `protobuf:"bytes,1,opt,name=contractAddr,proto3" json:"contractAddr,omitempty"`
	MemberAddr           *protos.TxAddr `protobuf:"bytes,2,opt,name=memberAddr,proto3" json:"memberAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueryContract) Reset()         { *m = QueryContract{} }
func (m *QueryContract) String() string { return proto.CompactTextString(m) }
func (*QueryContract) ProtoMessage()    {}
func (*QueryContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2978edb3d9b2dbe, []int{1}
}

func (m *QueryContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryContract.Unmarshal(m, b)
}
func (m *QueryContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryContract.Marshal(b, m, deterministic)
}
func (m *QueryContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryContract.Merge(m, src)
}
func (m *QueryContract) XXX_Size() int {
	return xxx_messageInfo_QueryContract.Size(m)
}
func (m *QueryContract) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryContract.DiscardUnknown(m)
}

var xxx_messageInfo_QueryContract proto.InternalMessageInfo

func (m *QueryContract) GetContractAddr() *protos.TxAddr {
	if m != nil {
		return m.ContractAddr
	}
	return nil
}

func (m *QueryContract) GetMemberAddr() *protos.TxAddr {
	if m != nil {
		return m.MemberAddr
	}
	return nil
}

type RedeemContract struct {
	Contract             *protos.TxAddr   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Amount               []byte           `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Redeems              []*protos.TxAddr `protobuf:"bytes,5,rep,name=redeems,proto3" json:"redeems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RedeemContract) Reset()         { *m = RedeemContract{} }
func (m *RedeemContract) String() string { return proto.CompactTextString(m) }
func (*RedeemContract) ProtoMessage()    {}
func (*RedeemContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2978edb3d9b2dbe, []int{2}
}

func (m *RedeemContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedeemContract.Unmarshal(m, b)
}
func (m *RedeemContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedeemContract.Marshal(b, m, deterministic)
}
func (m *RedeemContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedeemContract.Merge(m, src)
}
func (m *RedeemContract) XXX_Size() int {
	return xxx_messageInfo_RedeemContract.Size(m)
}
func (m *RedeemContract) XXX_DiscardUnknown() {
	xxx_messageInfo_RedeemContract.DiscardUnknown(m)
}

var xxx_messageInfo_RedeemContract proto.InternalMessageInfo

func (m *RedeemContract) GetContract() *protos.TxAddr {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *RedeemContract) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *RedeemContract) GetRedeems() []*protos.TxAddr {
	if m != nil {
		return m.Redeems
	}
	return nil
}

type RedeemResponse struct {
	Nonces               [][]byte `protobuf:"bytes,1,rep,name=nonces,proto3" json:"nonces,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedeemResponse) Reset()         { *m = RedeemResponse{} }
func (m *RedeemResponse) String() string { return proto.CompactTextString(m) }
func (*RedeemResponse) ProtoMessage()    {}
func (*RedeemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2978edb3d9b2dbe, []int{3}
}

func (m *RedeemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedeemResponse.Unmarshal(m, b)
}
func (m *RedeemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedeemResponse.Marshal(b, m, deterministic)
}
func (m *RedeemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedeemResponse.Merge(m, src)
}
func (m *RedeemResponse) XXX_Size() int {
	return xxx_messageInfo_RedeemResponse.Size(m)
}
func (m *RedeemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RedeemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RedeemResponse proto.InternalMessageInfo

func (m *RedeemResponse) GetNonces() [][]byte {
	if m != nil {
		return m.Nonces
	}
	return nil
}

type Contract struct {
	TotalRedeem          []byte                   `protobuf:"bytes,3,opt,name=totalRedeem,proto3" json:"totalRedeem,omitempty"`
	Status               []*Contract_MemberStatus `protobuf:"bytes,5,rep,name=status,proto3" json:"status,omitempty"`
	ContractTs           *timestamp.Timestamp     `protobuf:"bytes,6,opt,name=contractTs,proto3" json:"contractTs,omitempty"`
	FrozenTo             *timestamp.Timestamp     `protobuf:"bytes,8,opt,name=frozenTo,proto3" json:"frozenTo,omitempty"`
	TotalWeight          int64                    `protobuf:"varint,9,opt,name=totalWeight,proto3" json:"totalWeight,omitempty"`
	IsFrozen             bool                     `protobuf:"varint,10,opt,name=isFrozen,proto3" json:"isFrozen,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2978edb3d9b2dbe, []int{4}
}

func (m *Contract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contract.Unmarshal(m, b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return xxx_messageInfo_Contract.Size(m)
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetTotalRedeem() []byte {
	if m != nil {
		return m.TotalRedeem
	}
	return nil
}

func (m *Contract) GetStatus() []*Contract_MemberStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Contract) GetContractTs() *timestamp.Timestamp {
	if m != nil {
		return m.ContractTs
	}
	return nil
}

func (m *Contract) GetFrozenTo() *timestamp.Timestamp {
	if m != nil {
		return m.FrozenTo
	}
	return nil
}

func (m *Contract) GetTotalWeight() int64 {
	if m != nil {
		return m.TotalWeight
	}
	return 0
}

func (m *Contract) GetIsFrozen() bool {
	if m != nil {
		return m.IsFrozen
	}
	return false
}

type Contract_MemberStatus struct {
	Weight               int32          `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	TotalRedeem          []byte         `protobuf:"bytes,3,opt,name=totalRedeem,proto3" json:"totalRedeem,omitempty"`
	MemberID             *protos.TxAddr `protobuf:"bytes,5,opt,name=memberID,proto3" json:"memberID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Contract_MemberStatus) Reset()         { *m = Contract_MemberStatus{} }
func (m *Contract_MemberStatus) String() string { return proto.CompactTextString(m) }
func (*Contract_MemberStatus) ProtoMessage()    {}
func (*Contract_MemberStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2978edb3d9b2dbe, []int{4, 0}
}

func (m *Contract_MemberStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contract_MemberStatus.Unmarshal(m, b)
}
func (m *Contract_MemberStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contract_MemberStatus.Marshal(b, m, deterministic)
}
func (m *Contract_MemberStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract_MemberStatus.Merge(m, src)
}
func (m *Contract_MemberStatus) XXX_Size() int {
	return xxx_messageInfo_Contract_MemberStatus.Size(m)
}
func (m *Contract_MemberStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract_MemberStatus.DiscardUnknown(m)
}

var xxx_messageInfo_Contract_MemberStatus proto.InternalMessageInfo

func (m *Contract_MemberStatus) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Contract_MemberStatus) GetTotalRedeem() []byte {
	if m != nil {
		return m.TotalRedeem
	}
	return nil
}

func (m *Contract_MemberStatus) GetMemberID() *protos.TxAddr {
	if m != nil {
		return m.MemberID
	}
	return nil
}

func init() {
	proto.RegisterType((*RegContract)(nil), "ccshareprotos.RegContract")
	proto.RegisterType((*RegContract_Member)(nil), "ccshareprotos.RegContract.Member")
	proto.RegisterType((*QueryContract)(nil), "ccshareprotos.QueryContract")
	proto.RegisterType((*RedeemContract)(nil), "ccshareprotos.RedeemContract")
	proto.RegisterType((*RedeemResponse)(nil), "ccshareprotos.RedeemResponse")
	proto.RegisterType((*Contract)(nil), "ccshareprotos.Contract")
	proto.RegisterType((*Contract_MemberStatus)(nil), "ccshareprotos.Contract.MemberStatus")
}

func init() { proto.RegisterFile("subscriptiontx.proto", fileDescriptor_c2978edb3d9b2dbe) }

var fileDescriptor_c2978edb3d9b2dbe = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0xeb, 0xc6, 0xb8, 0x93, 0xb4, 0x87, 0x05, 0xa1, 0x95, 0x2f, 0x18, 0x8b, 0x83, 0x55,
	0xa1, 0x8d, 0x14, 0x24, 0x0e, 0x88, 0x4b, 0xa1, 0x20, 0x71, 0xe0, 0xc0, 0x12, 0x89, 0xb3, 0x63,
	0x4f, 0x5d, 0x4b, 0xb1, 0x37, 0xda, 0x5d, 0x8b, 0x94, 0x03, 0x1f, 0xc1, 0x57, 0xf1, 0x59, 0xc8,
	0xbb, 0x5e, 0xc7, 0x89, 0x12, 0xd1, 0x93, 0x35, 0x3b, 0xef, 0xbd, 0x99, 0x37, 0x7e, 0xf0, 0x4c,
	0xb5, 0x2b, 0x95, 0xcb, 0x6a, 0xa3, 0x2b, 0xd1, 0xe8, 0x2d, 0xdb, 0x48, 0xa1, 0x05, 0xb9, 0xcc,
	0x73, 0x75, 0x9f, 0x49, 0x34, 0x95, 0x8a, 0x9e, 0xda, 0xef, 0x5c, 0x6f, 0xb3, 0xa2, 0x90, 0x16,
	0x13, 0xbd, 0x28, 0x85, 0x28, 0xd7, 0x38, 0x37, 0xd5, 0xaa, 0xbd, 0x9b, 0xeb, 0xaa, 0x46, 0xa5,
	0xb3, 0x7a, 0x63, 0x01, 0xc9, 0x5f, 0x0f, 0xa6, 0x1c, 0xcb, 0x8f, 0xa2, 0xd1, 0x32, 0xcb, 0x35,
	0x79, 0x0d, 0x17, 0x05, 0xae, 0xb1, 0xcc, 0xb4, 0x90, 0xf4, 0x3c, 0xf6, 0xd2, 0xe9, 0xe2, 0xca,
	0x42, 0x15, 0x5b, 0x6e, 0x6f, 0x8a, 0x42, 0xf2, 0x1d, 0x80, 0x7c, 0x82, 0x59, 0xde, 0x33, 0x3f,
	0x88, 0xe2, 0x81, 0x4e, 0x62, 0x3f, 0x9d, 0x2e, 0x5e, 0xb2, 0xbd, 0xcd, 0xd8, 0x48, 0x9f, 0x7d,
	0xc5, 0x7a, 0x85, 0x92, 0xef, 0xd1, 0xa2, 0x5b, 0x08, 0xec, 0x3b, 0x49, 0xe0, 0xbc, 0xdb, 0x9e,
	0x7a, 0x47, 0x27, 0x9b, 0x1e, 0x79, 0x0e, 0xc1, 0x4f, 0xac, 0xca, 0x7b, 0x4d, 0xcf, 0x62, 0x2f,
	0x9d, 0xf0, 0xbe, 0x4a, 0x14, 0x5c, 0x7e, 0x6b, 0x51, 0x3e, 0x0c, 0x5e, 0x16, 0xbb, 0xed, 0x6e,
	0x4e, 0x8b, 0xee, 0x61, 0x08, 0x03, 0xa8, 0xcd, 0x2a, 0x86, 0x71, 0x76, 0x94, 0x31, 0x42, 0x24,
	0xbf, 0xe1, 0x8a, 0x63, 0x81, 0x58, 0x0f, 0x53, 0xaf, 0x21, 0x74, 0x8a, 0x27, 0x26, 0x0e, 0xfd,
	0xce, 0x4a, 0x56, 0x8b, 0xb6, 0xb1, 0x56, 0x66, 0xbc, 0xaf, 0x48, 0x0a, 0x4f, 0xa4, 0x51, 0x55,
	0xfd, 0x49, 0x0f, 0x25, 0x5c, 0x3b, 0x49, 0xdd, 0x7c, 0x8e, 0x6a, 0x23, 0x1a, 0x85, 0x9d, 0x66,
	0x23, 0x9a, 0x1c, 0x15, 0xf5, 0x62, 0xbf, 0xd3, 0xb4, 0x55, 0xf2, 0xc7, 0x87, 0x70, 0x58, 0x32,
	0x86, 0xa9, 0x16, 0x3a, 0x5b, 0x5b, 0x2e, 0xf5, 0xcd, 0xf4, 0xf1, 0x13, 0x79, 0x0f, 0x81, 0xd2,
	0x99, 0x6e, 0xdd, 0x06, 0xaf, 0x0e, 0x7e, 0xea, 0xc1, 0x1f, 0xfd, 0x6e, 0xb0, 0xbc, 0xe7, 0x90,
	0x77, 0x00, 0xce, 0xe4, 0x52, 0xd1, 0xc0, 0x9c, 0x21, 0x62, 0x36, 0x8c, 0xcc, 0x85, 0x91, 0x2d,
	0x5d, 0x18, 0xf9, 0x08, 0x4d, 0xde, 0x42, 0x78, 0x27, 0xc5, 0x2f, 0x6c, 0x96, 0x82, 0x86, 0xff,
	0x65, 0x0e, 0xd8, 0xc1, 0xd3, 0x0f, 0x1b, 0x8e, 0x8b, 0xd8, 0x4b, 0x7d, 0x3e, 0x7e, 0x22, 0x11,
	0x84, 0x95, 0xfa, 0x6c, 0xf0, 0x14, 0x62, 0x2f, 0x0d, 0xf9, 0x50, 0x47, 0x1a, 0x66, 0x63, 0x27,
	0xa7, 0x52, 0xf6, 0x88, 0xcb, 0x5d, 0x43, 0x68, 0x03, 0xf2, 0xe5, 0x96, 0x4e, 0x8e, 0x07, 0xc0,
	0xf5, 0x57, 0x81, 0x69, 0xbc, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0x69, 0x3f, 0x38, 0x79, 0xe2,
	0x03, 0x00, 0x00,
}
