// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tx.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TxBase struct {
	Network string `protobuf:"bytes,1,opt,name=network" json:"network,omitempty"`
	Ccname  string `protobuf:"bytes,2,opt,name=ccname" json:"ccname,omitempty"`
	Method  string `protobuf:"bytes,3,opt,name=method" json:"method,omitempty"`
}

func (m *TxBase) Reset()                    { *m = TxBase{} }
func (m *TxBase) String() string            { return proto.CompactTextString(m) }
func (*TxBase) ProtoMessage()               {}
func (*TxBase) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *TxBase) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *TxBase) GetCcname() string {
	if m != nil {
		return m.Ccname
	}
	return ""
}

func (m *TxBase) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type TxHeader struct {
	Base      *TxBase                    `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	ExpiredTs *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=expiredTs" json:"expiredTs,omitempty"`
	Nonce     []byte                     `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (m *TxHeader) Reset()                    { *m = TxHeader{} }
func (m *TxHeader) String() string            { return proto.CompactTextString(m) }
func (*TxHeader) ProtoMessage()               {}
func (*TxHeader) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *TxHeader) GetBase() *TxBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *TxHeader) GetExpiredTs() *google_protobuf.Timestamp {
	if m != nil {
		return m.ExpiredTs
	}
	return nil
}

func (m *TxHeader) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

type TxCredential struct {
	Addrc []*TxCredential_AddrCredentials `protobuf:"bytes,1,rep,name=addrc" json:"addrc,omitempty"`
}

func (m *TxCredential) Reset()                    { *m = TxCredential{} }
func (m *TxCredential) String() string            { return proto.CompactTextString(m) }
func (*TxCredential) ProtoMessage()               {}
func (*TxCredential) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *TxCredential) GetAddrc() []*TxCredential_AddrCredentials {
	if m != nil {
		return m.Addrc
	}
	return nil
}

type TxCredential_UserCredential struct {
	Signature *Signature `protobuf:"bytes,3,opt,name=signature" json:"signature,omitempty"`
}

func (m *TxCredential_UserCredential) Reset()                    { *m = TxCredential_UserCredential{} }
func (m *TxCredential_UserCredential) String() string            { return proto.CompactTextString(m) }
func (*TxCredential_UserCredential) ProtoMessage()               {}
func (*TxCredential_UserCredential) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 0} }

func (m *TxCredential_UserCredential) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type TxCredential_InnerCredential struct {
	Ccname      string `protobuf:"bytes,1,opt,name=ccname" json:"ccname,omitempty"`
	Fingerprint []byte `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
}

func (m *TxCredential_InnerCredential) Reset()                    { *m = TxCredential_InnerCredential{} }
func (m *TxCredential_InnerCredential) String() string            { return proto.CompactTextString(m) }
func (*TxCredential_InnerCredential) ProtoMessage()               {}
func (*TxCredential_InnerCredential) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 1} }

func (m *TxCredential_InnerCredential) GetCcname() string {
	if m != nil {
		return m.Ccname
	}
	return ""
}

func (m *TxCredential_InnerCredential) GetFingerprint() []byte {
	if m != nil {
		return m.Fingerprint
	}
	return nil
}

type TxCredential_AddrCredentials struct {
	// Types that are valid to be assigned to Cred:
	//	*TxCredential_AddrCredentials_User
	//	*TxCredential_AddrCredentials_Cc
	Cred isTxCredential_AddrCredentials_Cred `protobuf_oneof:"cred"`
}

func (m *TxCredential_AddrCredentials) Reset()                    { *m = TxCredential_AddrCredentials{} }
func (m *TxCredential_AddrCredentials) String() string            { return proto.CompactTextString(m) }
func (*TxCredential_AddrCredentials) ProtoMessage()               {}
func (*TxCredential_AddrCredentials) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 2} }

type isTxCredential_AddrCredentials_Cred interface {
	isTxCredential_AddrCredentials_Cred()
}

type TxCredential_AddrCredentials_User struct {
	User *TxCredential_UserCredential `protobuf:"bytes,1,opt,name=user,oneof"`
}
type TxCredential_AddrCredentials_Cc struct {
	Cc *TxCredential_InnerCredential `protobuf:"bytes,2,opt,name=cc,oneof"`
}

func (*TxCredential_AddrCredentials_User) isTxCredential_AddrCredentials_Cred() {}
func (*TxCredential_AddrCredentials_Cc) isTxCredential_AddrCredentials_Cred()   {}

func (m *TxCredential_AddrCredentials) GetCred() isTxCredential_AddrCredentials_Cred {
	if m != nil {
		return m.Cred
	}
	return nil
}

func (m *TxCredential_AddrCredentials) GetUser() *TxCredential_UserCredential {
	if x, ok := m.GetCred().(*TxCredential_AddrCredentials_User); ok {
		return x.User
	}
	return nil
}

func (m *TxCredential_AddrCredentials) GetCc() *TxCredential_InnerCredential {
	if x, ok := m.GetCred().(*TxCredential_AddrCredentials_Cc); ok {
		return x.Cc
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TxCredential_AddrCredentials) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TxCredential_AddrCredentials_OneofMarshaler, _TxCredential_AddrCredentials_OneofUnmarshaler, _TxCredential_AddrCredentials_OneofSizer, []interface{}{
		(*TxCredential_AddrCredentials_User)(nil),
		(*TxCredential_AddrCredentials_Cc)(nil),
	}
}

func _TxCredential_AddrCredentials_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TxCredential_AddrCredentials)
	// cred
	switch x := m.Cred.(type) {
	case *TxCredential_AddrCredentials_User:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.User); err != nil {
			return err
		}
	case *TxCredential_AddrCredentials_Cc:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Cc); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("TxCredential_AddrCredentials.Cred has unexpected type %T", x)
	}
	return nil
}

func _TxCredential_AddrCredentials_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TxCredential_AddrCredentials)
	switch tag {
	case 1: // cred.user
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TxCredential_UserCredential)
		err := b.DecodeMessage(msg)
		m.Cred = &TxCredential_AddrCredentials_User{msg}
		return true, err
	case 2: // cred.cc
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TxCredential_InnerCredential)
		err := b.DecodeMessage(msg)
		m.Cred = &TxCredential_AddrCredentials_Cc{msg}
		return true, err
	default:
		return false, nil
	}
}

func _TxCredential_AddrCredentials_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TxCredential_AddrCredentials)
	// cred
	switch x := m.Cred.(type) {
	case *TxCredential_AddrCredentials_User:
		s := proto.Size(x.User)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TxCredential_AddrCredentials_Cc:
		s := proto.Size(x.Cc)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type TxBatch struct {
	Txs []*TxBatchSubTx `protobuf:"bytes,1,rep,name=txs" json:"txs,omitempty"`
}

func (m *TxBatch) Reset()                    { *m = TxBatch{} }
func (m *TxBatch) String() string            { return proto.CompactTextString(m) }
func (*TxBatch) ProtoMessage()               {}
func (*TxBatch) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *TxBatch) GetTxs() []*TxBatchSubTx {
	if m != nil {
		return m.Txs
	}
	return nil
}

type TxBatchSubTx struct {
	Method  string `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *TxBatchSubTx) Reset()                    { *m = TxBatchSubTx{} }
func (m *TxBatchSubTx) String() string            { return proto.CompactTextString(m) }
func (*TxBatchSubTx) ProtoMessage()               {}
func (*TxBatchSubTx) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3, 0} }

func (m *TxBatchSubTx) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *TxBatchSubTx) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type TxBatchResp struct {
	Response [][]byte `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
}

func (m *TxBatchResp) Reset()                    { *m = TxBatchResp{} }
func (m *TxBatchResp) String() string            { return proto.CompactTextString(m) }
func (*TxBatchResp) ProtoMessage()               {}
func (*TxBatchResp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *TxBatchResp) GetResponse() [][]byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*TxBase)(nil), "protos.TxBase")
	proto.RegisterType((*TxHeader)(nil), "protos.TxHeader")
	proto.RegisterType((*TxCredential)(nil), "protos.TxCredential")
	proto.RegisterType((*TxCredential_UserCredential)(nil), "protos.TxCredential.UserCredential")
	proto.RegisterType((*TxCredential_InnerCredential)(nil), "protos.TxCredential.InnerCredential")
	proto.RegisterType((*TxCredential_AddrCredentials)(nil), "protos.TxCredential.AddrCredentials")
	proto.RegisterType((*TxBatch)(nil), "protos.TxBatch")
	proto.RegisterType((*TxBatchSubTx)(nil), "protos.TxBatch.subTx")
	proto.RegisterType((*TxBatchResp)(nil), "protos.TxBatchResp")
}

func init() { proto.RegisterFile("tx.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x37, 0xfd, 0xb7, 0xed, 0x24, 0xda, 0x15, 0x16, 0xa0, 0x28, 0x17, 0xaa, 0x80, 0x44,
	0xb9, 0xa4, 0x52, 0x91, 0x10, 0xcb, 0x6d, 0x97, 0x4b, 0x11, 0x37, 0x13, 0x1e, 0xc0, 0xb5, 0x67,
	0xdb, 0x88, 0xc6, 0x8e, 0x6c, 0x57, 0x64, 0x2f, 0x3c, 0x01, 0x2f, 0xca, 0x5b, 0xa0, 0xd8, 0xc9,
	0x26, 0x5d, 0xed, 0x29, 0xfa, 0xcd, 0x8c, 0x67, 0x3e, 0x7f, 0x9e, 0xc0, 0xdc, 0xd6, 0x59, 0xa5,
	0x95, 0x55, 0x64, 0xe6, 0x3e, 0x26, 0x89, 0xb8, 0x7e, 0xa8, 0xac, 0xf2, 0xd1, 0xe4, 0xcd, 0x5e,
	0xa9, 0xfd, 0x11, 0xd7, 0x8e, 0x76, 0xa7, 0xfb, 0xb5, 0x2d, 0x4a, 0x34, 0x96, 0x95, 0x95, 0x2f,
	0x48, 0x29, 0xcc, 0xf2, 0xfa, 0x8e, 0x19, 0x24, 0x31, 0x5c, 0x4a, 0xb4, 0xbf, 0x95, 0xfe, 0x15,
	0x07, 0xcb, 0x60, 0xb5, 0xa0, 0x1d, 0x92, 0xd7, 0x30, 0xe3, 0x5c, 0xb2, 0x12, 0xe3, 0x91, 0x4b,
	0xb4, 0xd4, 0xc4, 0x4b, 0xb4, 0x07, 0x25, 0xe2, 0xb1, 0x8f, 0x7b, 0x4a, 0xff, 0xc0, 0x3c, 0xaf,
	0xb7, 0xc8, 0x04, 0x6a, 0x92, 0xc2, 0x64, 0xc7, 0x0c, 0xba, 0x96, 0xe1, 0xe6, 0xca, 0x4f, 0x35,
	0x99, 0x9f, 0x49, 0x5d, 0x8e, 0x7c, 0x86, 0x05, 0xd6, 0x55, 0xa1, 0x51, 0xe4, 0xc6, 0x8d, 0x08,
	0x37, 0x49, 0xe6, 0x85, 0x67, 0x9d, 0xf0, 0x2c, 0xef, 0x84, 0xd3, 0xbe, 0x98, 0xbc, 0x84, 0xa9,
	0x54, 0x92, 0xa3, 0x13, 0x10, 0x51, 0x0f, 0xe9, 0xbf, 0x11, 0x44, 0x79, 0xfd, 0x55, 0xa3, 0x40,
	0x69, 0x0b, 0x76, 0x24, 0x5f, 0x60, 0xca, 0x84, 0xd0, 0x3c, 0x0e, 0x96, 0xe3, 0x55, 0xb8, 0x79,
	0xd7, 0xab, 0xe8, 0x8b, 0xb2, 0x5b, 0x21, 0x74, 0x8f, 0x86, 0xfa, 0x23, 0xc9, 0x2d, 0x5c, 0xfd,
	0x34, 0x38, 0xc8, 0x90, 0x35, 0x2c, 0x4c, 0xb1, 0x97, 0xcc, 0x9e, 0xb4, 0x1f, 0x1c, 0x6e, 0x5e,
	0x74, 0x1d, 0x7f, 0x74, 0x09, 0xda, 0xd7, 0x24, 0xdf, 0xe1, 0xfa, 0x9b, 0x94, 0x67, 0x3d, 0x7a,
	0x4b, 0x83, 0x33, 0x4b, 0x97, 0x10, 0xde, 0x17, 0x72, 0x8f, 0xba, 0xd2, 0x85, 0xb4, 0xce, 0x8c,
	0x88, 0x0e, 0x43, 0xc9, 0xdf, 0x00, 0xae, 0x9f, 0x48, 0x25, 0x37, 0x30, 0x39, 0x19, 0xd4, 0xad,
	0xc9, 0x6f, 0x9f, 0xbd, 0xde, 0xf9, 0x25, 0xb6, 0x17, 0xd4, 0x1d, 0x21, 0x9f, 0x60, 0xc4, 0x79,
	0x6b, 0xfa, 0xf3, 0xbe, 0x3c, 0x91, 0xbe, 0xbd, 0xa0, 0x23, 0xce, 0xef, 0x66, 0x30, 0xe1, 0x1a,
	0x45, 0x5a, 0xc2, 0x65, 0xf3, 0x96, 0x96, 0x1f, 0xc8, 0x7b, 0x18, 0xdb, 0xda, 0xb4, 0x1e, 0xbf,
	0x1a, 0xbe, 0xb4, 0xe5, 0x87, 0xcc, 0x9c, 0x76, 0x79, 0x4d, 0x9b, 0x8a, 0xe4, 0x06, 0xa6, 0x8e,
	0x06, 0x0b, 0x14, 0x0c, 0x17, 0xa8, 0x59, 0xc5, 0x8a, 0x3d, 0x1c, 0x15, 0x13, 0xad, 0x03, 0x1d,
	0xa6, 0x1f, 0x20, 0x6c, 0x1b, 0x52, 0x34, 0x15, 0x49, 0x60, 0xae, 0xd1, 0x54, 0x4a, 0xba, 0x0d,
	0x1b, 0xaf, 0x22, 0xfa, 0xc8, 0x3b, 0xff, 0x43, 0x7c, 0xfc, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xe4,
	0x82, 0x00, 0xda, 0x23, 0x03, 0x00, 0x00,
}
