// Code generated by protoc-gen-go. DO NOT EDIT.
// source: txaddr.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TxAddr struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxAddr) Reset()         { *m = TxAddr{} }
func (m *TxAddr) String() string { return proto.CompactTextString(m) }
func (*TxAddr) ProtoMessage()    {}
func (*TxAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_b785f6fe27629ef0, []int{0}
}

func (m *TxAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxAddr.Unmarshal(m, b)
}
func (m *TxAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxAddr.Marshal(b, m, deterministic)
}
func (m *TxAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxAddr.Merge(m, src)
}
func (m *TxAddr) XXX_Size() int {
	return xxx_messageInfo_TxAddr.Size(m)
}
func (m *TxAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_TxAddr.DiscardUnknown(m)
}

var xxx_messageInfo_TxAddr proto.InternalMessageInfo

func (m *TxAddr) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type TxMsgExample struct {
	Param1               []byte   `protobuf:"bytes,1,opt,name=param1,proto3" json:"param1,omitempty"`
	Param2               int32    `protobuf:"varint,2,opt,name=param2,proto3" json:"param2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxMsgExample) Reset()         { *m = TxMsgExample{} }
func (m *TxMsgExample) String() string { return proto.CompactTextString(m) }
func (*TxMsgExample) ProtoMessage()    {}
func (*TxMsgExample) Descriptor() ([]byte, []int) {
	return fileDescriptor_b785f6fe27629ef0, []int{1}
}

func (m *TxMsgExample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxMsgExample.Unmarshal(m, b)
}
func (m *TxMsgExample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxMsgExample.Marshal(b, m, deterministic)
}
func (m *TxMsgExample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxMsgExample.Merge(m, src)
}
func (m *TxMsgExample) XXX_Size() int {
	return xxx_messageInfo_TxMsgExample.Size(m)
}
func (m *TxMsgExample) XXX_DiscardUnknown() {
	xxx_messageInfo_TxMsgExample.DiscardUnknown(m)
}

var xxx_messageInfo_TxMsgExample proto.InternalMessageInfo

func (m *TxMsgExample) GetParam1() []byte {
	if m != nil {
		return m.Param1
	}
	return nil
}

func (m *TxMsgExample) GetParam2() int32 {
	if m != nil {
		return m.Param2
	}
	return 0
}

func init() {
	proto.RegisterType((*TxAddr)(nil), "protos.TxAddr")
	proto.RegisterType((*TxMsgExample)(nil), "protos.TxMsgExample")
}

func init() { proto.RegisterFile("txaddr.proto", fileDescriptor_b785f6fe27629ef0) }

var fileDescriptor_b785f6fe27629ef0 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xa9, 0x48, 0x4c,
	0x49, 0x29, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0x32, 0x5c,
	0x6c, 0x21, 0x15, 0x8e, 0x29, 0x29, 0x45, 0x42, 0x42, 0x5c, 0x2c, 0x19, 0x89, 0xc5, 0x19, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x60, 0xb6, 0x92, 0x1d, 0x17, 0x4f, 0x48, 0x85, 0x6f, 0x71,
	0xba, 0x6b, 0x45, 0x62, 0x6e, 0x41, 0x4e, 0xaa, 0x90, 0x18, 0x17, 0x5b, 0x41, 0x62, 0x51, 0x62,
	0xae, 0x21, 0x54, 0x15, 0x94, 0x07, 0x17, 0x37, 0x92, 0x60, 0x52, 0x60, 0xd4, 0x60, 0x85, 0x8a,
	0x1b, 0x39, 0x29, 0x44, 0xc9, 0x65, 0x54, 0x16, 0xa4, 0x16, 0xe5, 0xa4, 0xa6, 0xa4, 0xa7, 0x16,
	0xe9, 0x25, 0x26, 0x25, 0x67, 0x24, 0x66, 0xe6, 0xe9, 0xe5, 0x17, 0xa5, 0xeb, 0x43, 0xec, 0x4f,
	0x82, 0xb8, 0xc3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x83, 0xc3, 0xc5, 0x9e, 0x00, 0x00,
	0x00,
}
