FROM abchain/fabric-baseimage:latest

# Copy config files
COPY membersrvc.yaml $GOPATH/src/github.com/abchain/fabric/membersrvc/
COPY membersrvc.key /var/hyperledger/
COPY membersrvc.crt /var/hyperledger/

