FROM golang:1.9

RUN apt-get update \
        && apt-get install -y libsnappy-dev zlib1g-dev libbz2-dev \
        && rm -rf /var/cache/apt

# install rocksdb
RUN cd /tmp \
        && git clone --single-branch -b fabric-0.6 --depth 1 https://github.com/noel2004/rocksdb \
        && cd rocksdb \
        && PORTABLE=1 make shared_lib \
        && INSTALL_PATH=/usr/local make install-shared \
        && ldconfig \
        && rm -rf /tmp/rocksdb

# Set workdir and env
WORKDIR /opt/gopath
ENV GOPATH=/opt/gopath

# clone hyperledger
RUN go get -d hyperledger.abchain.org/utils
# Build membersrvc, peer in legacy
RUN go get -d github.com/abchain/fabric/protos
RUN cd /opt/gopath/github.com/abchain/fabric \
        && git checkout fabric-legacy
RUN go install github.com/abchain/fabric/membersrvc
RUN go install github.com/abchain/fabric/peer

# Install membersrvc and peer to $PATH
RUN cp $GOPATH/bin/membersrvc /usr/bin/ \
    && cp $GOPATH/bin/peer /usr/bin/

# Clear
RUN rm -rf $GOPATH/pkg

