// Code generated by protoc-gen-go. DO NOT EDIT.
// source: persistent.proto

/*
Package ccprotos is a generated protocol buffer package.

It is generated from these files:
	persistent.proto
	tokentx.proto

It has these top-level messages:
	FuncRecord
	AccountData
	NonceData
	TokenGlobalData
	SimpleFund
	QueryToken
	QueryTransfer
	QueryGlobal
	BaseToken
	Assign
*/
package ccprotos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FuncRecord struct {
	Noncekey []byte `protobuf:"bytes,1,opt,name=noncekey,proto3" json:"noncekey,omitempty"`
	IsSend   bool   `protobuf:"varint,2,opt,name=isSend" json:"isSend,omitempty"`
}

func (m *FuncRecord) Reset()                    { *m = FuncRecord{} }
func (m *FuncRecord) String() string            { return proto.CompactTextString(m) }
func (*FuncRecord) ProtoMessage()               {}
func (*FuncRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FuncRecord) GetNoncekey() []byte {
	if m != nil {
		return m.Noncekey
	}
	return nil
}

func (m *FuncRecord) GetIsSend() bool {
	if m != nil {
		return m.IsSend
	}
	return false
}

type AccountData struct {
	Balance  []byte      `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	LastFund *FuncRecord `protobuf:"bytes,2,opt,name=lastFund" json:"lastFund,omitempty"`
}

func (m *AccountData) Reset()                    { *m = AccountData{} }
func (m *AccountData) String() string            { return proto.CompactTextString(m) }
func (*AccountData) ProtoMessage()               {}
func (*AccountData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AccountData) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *AccountData) GetLastFund() *FuncRecord {
	if m != nil {
		return m.LastFund
	}
	return nil
}

type NonceData struct {
	Txid      string                     `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
	Amount    []byte                     `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	FromLast  *FuncRecord                `protobuf:"bytes,3,opt,name=fromLast" json:"fromLast,omitempty"`
	ToLast    *FuncRecord                `protobuf:"bytes,4,opt,name=toLast" json:"toLast,omitempty"`
	NonceTime *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=nonceTime" json:"nonceTime,omitempty"`
}

func (m *NonceData) Reset()                    { *m = NonceData{} }
func (m *NonceData) String() string            { return proto.CompactTextString(m) }
func (*NonceData) ProtoMessage()               {}
func (*NonceData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NonceData) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *NonceData) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *NonceData) GetFromLast() *FuncRecord {
	if m != nil {
		return m.FromLast
	}
	return nil
}

func (m *NonceData) GetToLast() *FuncRecord {
	if m != nil {
		return m.ToLast
	}
	return nil
}

func (m *NonceData) GetNonceTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.NonceTime
	}
	return nil
}

type TokenGlobalData struct {
	TotalTokens      []byte `protobuf:"bytes,10,opt,name=totalTokens,proto3" json:"totalTokens,omitempty"`
	UnassignedTokens []byte `protobuf:"bytes,11,opt,name=unassignedTokens,proto3" json:"unassignedTokens,omitempty"`
}

func (m *TokenGlobalData) Reset()                    { *m = TokenGlobalData{} }
func (m *TokenGlobalData) String() string            { return proto.CompactTextString(m) }
func (*TokenGlobalData) ProtoMessage()               {}
func (*TokenGlobalData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TokenGlobalData) GetTotalTokens() []byte {
	if m != nil {
		return m.TotalTokens
	}
	return nil
}

func (m *TokenGlobalData) GetUnassignedTokens() []byte {
	if m != nil {
		return m.UnassignedTokens
	}
	return nil
}

func init() {
	proto.RegisterType((*FuncRecord)(nil), "ccprotos.FuncRecord")
	proto.RegisterType((*AccountData)(nil), "ccprotos.AccountData")
	proto.RegisterType((*NonceData)(nil), "ccprotos.NonceData")
	proto.RegisterType((*TokenGlobalData)(nil), "ccprotos.TokenGlobalData")
}

func init() { proto.RegisterFile("persistent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x89, 0x96, 0x98, 0x4e, 0x0a, 0x96, 0x45, 0x24, 0xf4, 0x62, 0xc9, 0xa9, 0x88, 0xa4,
	0xa2, 0x17, 0x8f, 0x0a, 0x52, 0x2f, 0xe2, 0x61, 0xed, 0xc5, 0x93, 0x6c, 0x36, 0xdb, 0x12, 0x9a,
	0xec, 0x94, 0xec, 0x04, 0xf4, 0x67, 0xfa, 0x8f, 0x24, 0xd3, 0x4d, 0x2b, 0x08, 0xbd, 0xed, 0x1b,
	0xbe, 0x7d, 0x6f, 0xe6, 0xc1, 0x78, 0x6b, 0x1a, 0x57, 0x3a, 0x32, 0x96, 0xb2, 0x6d, 0x83, 0x84,
	0x22, 0xd2, 0x9a, 0x1f, 0x6e, 0x72, 0xb5, 0x46, 0x5c, 0x57, 0x66, 0xce, 0x32, 0x6f, 0x57, 0x73,
	0x2a, 0x6b, 0xe3, 0x48, 0xd5, 0xdb, 0x1d, 0x9a, 0x3e, 0x02, 0x2c, 0x5a, 0xab, 0xa5, 0xd1, 0xd8,
	0x14, 0x62, 0x02, 0x91, 0x45, 0xab, 0xcd, 0xc6, 0x7c, 0x27, 0xc1, 0x34, 0x98, 0x8d, 0xe4, 0x5e,
	0x8b, 0x4b, 0x08, 0x4b, 0xf7, 0x6e, 0x6c, 0x91, 0x9c, 0x4c, 0x83, 0x59, 0x24, 0xbd, 0x4a, 0x3f,
	0x20, 0x7e, 0xd2, 0x1a, 0x5b, 0x4b, 0xcf, 0x8a, 0x94, 0x48, 0xe0, 0x2c, 0x57, 0x95, 0xb2, 0xda,
	0x78, 0x87, 0x5e, 0x8a, 0x5b, 0x88, 0x2a, 0xe5, 0x68, 0xd1, 0x7a, 0x8b, 0xf8, 0xee, 0x22, 0xeb,
	0x17, 0xcd, 0x0e, 0x4b, 0xc8, 0x3d, 0x95, 0xfe, 0x04, 0x30, 0x7c, 0xeb, 0xf2, 0xd9, 0x59, 0xc0,
	0x80, 0xbe, 0xca, 0x82, 0x6d, 0x87, 0x92, 0xdf, 0xdd, 0x52, 0xaa, 0xee, 0xb2, 0xd9, 0x71, 0x24,
	0xbd, 0xea, 0xb2, 0x56, 0x0d, 0xd6, 0xaf, 0xca, 0x51, 0x72, 0x7a, 0x2c, 0xab, 0xa7, 0xc4, 0x0d,
	0x84, 0x84, 0xcc, 0x0f, 0x8e, 0xf0, 0x9e, 0x11, 0x0f, 0x30, 0xe4, 0x62, 0x96, 0x65, 0x6d, 0x92,
	0x90, 0x3f, 0x4c, 0xb2, 0x5d, 0xd7, 0x59, 0xdf, 0x75, 0xb6, 0xec, 0xbb, 0x96, 0x07, 0x38, 0xfd,
	0x84, 0xf3, 0x25, 0x6e, 0x8c, 0x7d, 0xa9, 0x30, 0x57, 0x15, 0x1f, 0x36, 0x85, 0x98, 0x90, 0x54,
	0xc5, 0x73, 0x97, 0x00, 0x5f, 0xf2, 0x77, 0x24, 0xae, 0x61, 0xdc, 0x5a, 0xe5, 0x5c, 0xb9, 0xb6,
	0xa6, 0xf0, 0x58, 0xcc, 0xd8, 0xbf, 0x79, 0x1e, 0x72, 0xfe, 0xfd, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf0, 0x17, 0x71, 0x86, 0x17, 0x02, 0x00, 0x00,
}
