// Code generated by protoc-gen-go. DO NOT EDIT.
// source: multisign.proto

package ccauthprotos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	protos "hyperledger.abchain.org/protos"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddrByWeight struct {
	Addr                 *protos.TxAddr `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Weight               int32          `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddrByWeight) Reset()         { *m = AddrByWeight{} }
func (m *AddrByWeight) String() string { return proto.CompactTextString(m) }
func (*AddrByWeight) ProtoMessage()    {}
func (*AddrByWeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fbe4b688817da51, []int{0}
}

func (m *AddrByWeight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddrByWeight.Unmarshal(m, b)
}
func (m *AddrByWeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddrByWeight.Marshal(b, m, deterministic)
}
func (m *AddrByWeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddrByWeight.Merge(m, src)
}
func (m *AddrByWeight) XXX_Size() int {
	return xxx_messageInfo_AddrByWeight.Size(m)
}
func (m *AddrByWeight) XXX_DiscardUnknown() {
	xxx_messageInfo_AddrByWeight.DiscardUnknown(m)
}

var xxx_messageInfo_AddrByWeight proto.InternalMessageInfo

func (m *AddrByWeight) GetAddr() *protos.TxAddr {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *AddrByWeight) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type Contract struct {
	Threshold            int32           `protobuf:"varint,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Addrs                []*AddrByWeight `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fbe4b688817da51, []int{1}
}

func (m *Contract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contract.Unmarshal(m, b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return xxx_messageInfo_Contract.Size(m)
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetThreshold() int32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *Contract) GetAddrs() []*AddrByWeight {
	if m != nil {
		return m.Addrs
	}
	return nil
}

type Update struct {
	Addr                 *protos.TxAddr `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	From                 *protos.TxAddr `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   *protos.TxAddr `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fbe4b688817da51, []int{2}
}

func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (m *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(m, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

func (m *Update) GetAddr() *protos.TxAddr {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *Update) GetFrom() *protos.TxAddr {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Update) GetTo() *protos.TxAddr {
	if m != nil {
		return m.To
	}
	return nil
}

func init() {
	proto.RegisterType((*AddrByWeight)(nil), "ccauthprotos.AddrByWeight")
	proto.RegisterType((*Contract)(nil), "ccauthprotos.Contract")
	proto.RegisterType((*Update)(nil), "ccauthprotos.Update")
}

func init() { proto.RegisterFile("multisign.proto", fileDescriptor_8fbe4b688817da51) }

var fileDescriptor_8fbe4b688817da51 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8e, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x69, 0x76, 0x5b, 0x74, 0x76, 0x51, 0x88, 0x20, 0x61, 0x11, 0x29, 0x39, 0xf5, 0x14,
	0x65, 0xfd, 0x05, 0xea, 0xcd, 0x63, 0x50, 0x04, 0x6f, 0xb1, 0xa9, 0x9b, 0xc2, 0xb6, 0x29, 0xc9,
	0x14, 0xeb, 0xbf, 0x97, 0x24, 0x82, 0x3d, 0xf4, 0xb0, 0xa7, 0x61, 0xde, 0xfb, 0x78, 0x7c, 0x70,
	0xd9, 0x8d, 0x47, 0x6c, 0x7d, 0x7b, 0xe8, 0xc5, 0xe0, 0x2c, 0x5a, 0xba, 0xad, 0x6b, 0x35, 0xa2,
	0x89, 0x8f, 0xdf, 0x5d, 0xa5, 0x7b, 0x87, 0x93, 0xd2, 0xda, 0x25, 0x84, 0xbf, 0xc0, 0xf6, 0x51,
	0x6b, 0xf7, 0xf4, 0xf3, 0xde, 0xb4, 0x07, 0x83, 0x94, 0xc3, 0x3a, 0xb4, 0x2c, 0x2b, 0xb3, 0x6a,
	0xb3, 0xbf, 0x48, 0x94, 0x17, 0xaf, 0x53, 0xa0, 0x64, 0xec, 0xe8, 0x35, 0x14, 0xdf, 0x91, 0x66,
	0xa4, 0xcc, 0xaa, 0x5c, 0xfe, 0x7d, 0xfc, 0x03, 0xce, 0x9e, 0x6d, 0x8f, 0x4e, 0xd5, 0x48, 0x6f,
	0xe0, 0x1c, 0x8d, 0x6b, 0xbc, 0xb1, 0x47, 0x1d, 0xc7, 0x72, 0xf9, 0x1f, 0xd0, 0x7b, 0xc8, 0xc3,
	0x92, 0x67, 0xa4, 0x5c, 0x55, 0x9b, 0xfd, 0x4e, 0xcc, 0x45, 0xc5, 0x5c, 0x48, 0x26, 0x90, 0x0f,
	0x50, 0xbc, 0x0d, 0x5a, 0x61, 0x73, 0x92, 0x21, 0x87, 0xf5, 0x97, 0xb3, 0x5d, 0xf4, 0x5b, 0x60,
	0x42, 0x47, 0x6f, 0x81, 0xa0, 0x65, 0xab, 0x45, 0x82, 0xa0, 0xfd, 0x2c, 0x62, 0xf4, 0xf0, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0xac, 0x38, 0x06, 0x91, 0x56, 0x01, 0x00, 0x00,
}
